// Code generated by protoc-gen-go. DO NOT EDIT.
// versions:
// 	protoc-gen-go v1.34.2
// 	protoc        v4.25.1
// source: tag-api.proto

package grpc

import (
	protoreflect "google.golang.org/protobuf/reflect/protoreflect"
	protoimpl "google.golang.org/protobuf/runtime/protoimpl"
	emptypb "google.golang.org/protobuf/types/known/emptypb"
	timestamppb "google.golang.org/protobuf/types/known/timestamppb"
	reflect "reflect"
	sync "sync"
)

const (
	// Verify that this generated code is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(20 - protoimpl.MinVersion)
	// Verify that runtime/protoimpl is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(protoimpl.MaxVersion - 20)
)

type AddAuthorizedCardsRequest struct {
	state         protoimpl.MessageState
	sizeCache     protoimpl.SizeCache
	unknownFields protoimpl.UnknownFields

	AuthorizedCards []*AuthorizedCard `protobuf:"bytes,1,rep,name=AuthorizedCards,proto3" json:"AuthorizedCards,omitempty"`
}

func (x *AddAuthorizedCardsRequest) Reset() {
	*x = AddAuthorizedCardsRequest{}
	if protoimpl.UnsafeEnabled {
		mi := &file_tag_api_proto_msgTypes[0]
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		ms.StoreMessageInfo(mi)
	}
}

func (x *AddAuthorizedCardsRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*AddAuthorizedCardsRequest) ProtoMessage() {}

func (x *AddAuthorizedCardsRequest) ProtoReflect() protoreflect.Message {
	mi := &file_tag_api_proto_msgTypes[0]
	if protoimpl.UnsafeEnabled && x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use AddAuthorizedCardsRequest.ProtoReflect.Descriptor instead.
func (*AddAuthorizedCardsRequest) Descriptor() ([]byte, []int) {
	return file_tag_api_proto_rawDescGZIP(), []int{0}
}

func (x *AddAuthorizedCardsRequest) GetAuthorizedCards() []*AuthorizedCard {
	if x != nil {
		return x.AuthorizedCards
	}
	return nil
}

type AddAuthorizedCardsResponse struct {
	state         protoimpl.MessageState
	sizeCache     protoimpl.SizeCache
	unknownFields protoimpl.UnknownFields

	Status []string `protobuf:"bytes,1,rep,name=status,proto3" json:"status,omitempty"`
}

func (x *AddAuthorizedCardsResponse) Reset() {
	*x = AddAuthorizedCardsResponse{}
	if protoimpl.UnsafeEnabled {
		mi := &file_tag_api_proto_msgTypes[1]
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		ms.StoreMessageInfo(mi)
	}
}

func (x *AddAuthorizedCardsResponse) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*AddAuthorizedCardsResponse) ProtoMessage() {}

func (x *AddAuthorizedCardsResponse) ProtoReflect() protoreflect.Message {
	mi := &file_tag_api_proto_msgTypes[1]
	if protoimpl.UnsafeEnabled && x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use AddAuthorizedCardsResponse.ProtoReflect.Descriptor instead.
func (*AddAuthorizedCardsResponse) Descriptor() ([]byte, []int) {
	return file_tag_api_proto_rawDescGZIP(), []int{1}
}

func (x *AddAuthorizedCardsResponse) GetStatus() []string {
	if x != nil {
		return x.Status
	}
	return nil
}

type GetAuthorizedCardsResponse struct {
	state         protoimpl.MessageState
	sizeCache     protoimpl.SizeCache
	unknownFields protoimpl.UnknownFields

	Version         int32             `protobuf:"varint,1,opt,name=Version,proto3" json:"Version,omitempty"`
	AuthorizedCards []*AuthorizedCard `protobuf:"bytes,2,rep,name=AuthorizedCards,proto3" json:"AuthorizedCards,omitempty"`
}

func (x *GetAuthorizedCardsResponse) Reset() {
	*x = GetAuthorizedCardsResponse{}
	if protoimpl.UnsafeEnabled {
		mi := &file_tag_api_proto_msgTypes[2]
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		ms.StoreMessageInfo(mi)
	}
}

func (x *GetAuthorizedCardsResponse) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*GetAuthorizedCardsResponse) ProtoMessage() {}

func (x *GetAuthorizedCardsResponse) ProtoReflect() protoreflect.Message {
	mi := &file_tag_api_proto_msgTypes[2]
	if protoimpl.UnsafeEnabled && x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use GetAuthorizedCardsResponse.ProtoReflect.Descriptor instead.
func (*GetAuthorizedCardsResponse) Descriptor() ([]byte, []int) {
	return file_tag_api_proto_rawDescGZIP(), []int{2}
}

func (x *GetAuthorizedCardsResponse) GetVersion() int32 {
	if x != nil {
		return x.Version
	}
	return 0
}

func (x *GetAuthorizedCardsResponse) GetAuthorizedCards() []*AuthorizedCard {
	if x != nil {
		return x.AuthorizedCards
	}
	return nil
}

type RemoveCardRequest struct {
	state         protoimpl.MessageState
	sizeCache     protoimpl.SizeCache
	unknownFields protoimpl.UnknownFields

	TagId string `protobuf:"bytes,1,opt,name=TagId,proto3" json:"TagId,omitempty"`
}

func (x *RemoveCardRequest) Reset() {
	*x = RemoveCardRequest{}
	if protoimpl.UnsafeEnabled {
		mi := &file_tag_api_proto_msgTypes[3]
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		ms.StoreMessageInfo(mi)
	}
}

func (x *RemoveCardRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*RemoveCardRequest) ProtoMessage() {}

func (x *RemoveCardRequest) ProtoReflect() protoreflect.Message {
	mi := &file_tag_api_proto_msgTypes[3]
	if protoimpl.UnsafeEnabled && x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use RemoveCardRequest.ProtoReflect.Descriptor instead.
func (*RemoveCardRequest) Descriptor() ([]byte, []int) {
	return file_tag_api_proto_rawDescGZIP(), []int{3}
}

func (x *RemoveCardRequest) GetTagId() string {
	if x != nil {
		return x.TagId
	}
	return ""
}

type RemoveCardResponse struct {
	state         protoimpl.MessageState
	sizeCache     protoimpl.SizeCache
	unknownFields protoimpl.UnknownFields

	Status ResponseStatus `protobuf:"varint,1,opt,name=Status,proto3,enum=api.ResponseStatus" json:"Status,omitempty"`
}

func (x *RemoveCardResponse) Reset() {
	*x = RemoveCardResponse{}
	if protoimpl.UnsafeEnabled {
		mi := &file_tag_api_proto_msgTypes[4]
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		ms.StoreMessageInfo(mi)
	}
}

func (x *RemoveCardResponse) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*RemoveCardResponse) ProtoMessage() {}

func (x *RemoveCardResponse) ProtoReflect() protoreflect.Message {
	mi := &file_tag_api_proto_msgTypes[4]
	if protoimpl.UnsafeEnabled && x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use RemoveCardResponse.ProtoReflect.Descriptor instead.
func (*RemoveCardResponse) Descriptor() ([]byte, []int) {
	return file_tag_api_proto_rawDescGZIP(), []int{4}
}

func (x *RemoveCardResponse) GetStatus() ResponseStatus {
	if x != nil {
		return x.Status
	}
	return ResponseStatus_Success
}

type AuthorizationHistoryResponse struct {
	state         protoimpl.MessageState
	sizeCache     protoimpl.SizeCache
	unknownFields protoimpl.UnknownFields

	History []*AuthorizationHistoryEntry `protobuf:"bytes,1,rep,name=History,proto3" json:"History,omitempty"`
}

func (x *AuthorizationHistoryResponse) Reset() {
	*x = AuthorizationHistoryResponse{}
	if protoimpl.UnsafeEnabled {
		mi := &file_tag_api_proto_msgTypes[5]
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		ms.StoreMessageInfo(mi)
	}
}

func (x *AuthorizationHistoryResponse) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*AuthorizationHistoryResponse) ProtoMessage() {}

func (x *AuthorizationHistoryResponse) ProtoReflect() protoreflect.Message {
	mi := &file_tag_api_proto_msgTypes[5]
	if protoimpl.UnsafeEnabled && x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use AuthorizationHistoryResponse.ProtoReflect.Descriptor instead.
func (*AuthorizationHistoryResponse) Descriptor() ([]byte, []int) {
	return file_tag_api_proto_rawDescGZIP(), []int{5}
}

func (x *AuthorizationHistoryResponse) GetHistory() []*AuthorizationHistoryEntry {
	if x != nil {
		return x.History
	}
	return nil
}

type AuthorizationHistoryEntry struct {
	state         protoimpl.MessageState
	sizeCache     protoimpl.SizeCache
	unknownFields protoimpl.UnknownFields

	Timestamp *timestamppb.Timestamp `protobuf:"bytes,1,opt,name=Timestamp,proto3" json:"Timestamp,omitempty"`
	TagId     string                 `protobuf:"bytes,2,opt,name=TagId,proto3" json:"TagId,omitempty"`
	Status    string                 `protobuf:"bytes,3,opt,name=Status,proto3" json:"Status,omitempty"`
}

func (x *AuthorizationHistoryEntry) Reset() {
	*x = AuthorizationHistoryEntry{}
	if protoimpl.UnsafeEnabled {
		mi := &file_tag_api_proto_msgTypes[6]
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		ms.StoreMessageInfo(mi)
	}
}

func (x *AuthorizationHistoryEntry) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*AuthorizationHistoryEntry) ProtoMessage() {}

func (x *AuthorizationHistoryEntry) ProtoReflect() protoreflect.Message {
	mi := &file_tag_api_proto_msgTypes[6]
	if protoimpl.UnsafeEnabled && x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use AuthorizationHistoryEntry.ProtoReflect.Descriptor instead.
func (*AuthorizationHistoryEntry) Descriptor() ([]byte, []int) {
	return file_tag_api_proto_rawDescGZIP(), []int{6}
}

func (x *AuthorizationHistoryEntry) GetTimestamp() *timestamppb.Timestamp {
	if x != nil {
		return x.Timestamp
	}
	return nil
}

func (x *AuthorizationHistoryEntry) GetTagId() string {
	if x != nil {
		return x.TagId
	}
	return ""
}

func (x *AuthorizationHistoryEntry) GetStatus() string {
	if x != nil {
		return x.Status
	}
	return ""
}

type AuthorizedCard struct {
	state         protoimpl.MessageState
	sizeCache     protoimpl.SizeCache
	unknownFields protoimpl.UnknownFields

	TagId      string                 `protobuf:"bytes,1,opt,name=TagId,proto3" json:"TagId,omitempty"`
	Status     string                 `protobuf:"bytes,2,opt,name=Status,proto3" json:"Status,omitempty"`
	ExpiryDate *timestamppb.Timestamp `protobuf:"bytes,3,opt,name=ExpiryDate,proto3,oneof" json:"ExpiryDate,omitempty"`
}

func (x *AuthorizedCard) Reset() {
	*x = AuthorizedCard{}
	if protoimpl.UnsafeEnabled {
		mi := &file_tag_api_proto_msgTypes[7]
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		ms.StoreMessageInfo(mi)
	}
}

func (x *AuthorizedCard) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*AuthorizedCard) ProtoMessage() {}

func (x *AuthorizedCard) ProtoReflect() protoreflect.Message {
	mi := &file_tag_api_proto_msgTypes[7]
	if protoimpl.UnsafeEnabled && x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use AuthorizedCard.ProtoReflect.Descriptor instead.
func (*AuthorizedCard) Descriptor() ([]byte, []int) {
	return file_tag_api_proto_rawDescGZIP(), []int{7}
}

func (x *AuthorizedCard) GetTagId() string {
	if x != nil {
		return x.TagId
	}
	return ""
}

func (x *AuthorizedCard) GetStatus() string {
	if x != nil {
		return x.Status
	}
	return ""
}

func (x *AuthorizedCard) GetExpiryDate() *timestamppb.Timestamp {
	if x != nil {
		return x.ExpiryDate
	}
	return nil
}

var File_tag_api_proto protoreflect.FileDescriptor

var file_tag_api_proto_rawDesc = []byte{
	0x0a, 0x0d, 0x74, 0x61, 0x67, 0x2d, 0x61, 0x70, 0x69, 0x2e, 0x70, 0x72, 0x6f, 0x74, 0x6f, 0x12,
	0x03, 0x61, 0x70, 0x69, 0x1a, 0x1b, 0x67, 0x6f, 0x6f, 0x67, 0x6c, 0x65, 0x2f, 0x70, 0x72, 0x6f,
	0x74, 0x6f, 0x62, 0x75, 0x66, 0x2f, 0x65, 0x6d, 0x70, 0x74, 0x79, 0x2e, 0x70, 0x72, 0x6f, 0x74,
	0x6f, 0x1a, 0x1f, 0x67, 0x6f, 0x6f, 0x67, 0x6c, 0x65, 0x2f, 0x70, 0x72, 0x6f, 0x74, 0x6f, 0x62,
	0x75, 0x66, 0x2f, 0x74, 0x69, 0x6d, 0x65, 0x73, 0x74, 0x61, 0x6d, 0x70, 0x2e, 0x70, 0x72, 0x6f,
	0x74, 0x6f, 0x1a, 0x0b, 0x65, 0x6e, 0x75, 0x6d, 0x73, 0x2e, 0x70, 0x72, 0x6f, 0x74, 0x6f, 0x22,
	0x5a, 0x0a, 0x19, 0x41, 0x64, 0x64, 0x41, 0x75, 0x74, 0x68, 0x6f, 0x72, 0x69, 0x7a, 0x65, 0x64,
	0x43, 0x61, 0x72, 0x64, 0x73, 0x52, 0x65, 0x71, 0x75, 0x65, 0x73, 0x74, 0x12, 0x3d, 0x0a, 0x0f,
	0x41, 0x75, 0x74, 0x68, 0x6f, 0x72, 0x69, 0x7a, 0x65, 0x64, 0x43, 0x61, 0x72, 0x64, 0x73, 0x18,
	0x01, 0x20, 0x03, 0x28, 0x0b, 0x32, 0x13, 0x2e, 0x61, 0x70, 0x69, 0x2e, 0x41, 0x75, 0x74, 0x68,
	0x6f, 0x72, 0x69, 0x7a, 0x65, 0x64, 0x43, 0x61, 0x72, 0x64, 0x52, 0x0f, 0x41, 0x75, 0x74, 0x68,
	0x6f, 0x72, 0x69, 0x7a, 0x65, 0x64, 0x43, 0x61, 0x72, 0x64, 0x73, 0x22, 0x34, 0x0a, 0x1a, 0x41,
	0x64, 0x64, 0x41, 0x75, 0x74, 0x68, 0x6f, 0x72, 0x69, 0x7a, 0x65, 0x64, 0x43, 0x61, 0x72, 0x64,
	0x73, 0x52, 0x65, 0x73, 0x70, 0x6f, 0x6e, 0x73, 0x65, 0x12, 0x16, 0x0a, 0x06, 0x73, 0x74, 0x61,
	0x74, 0x75, 0x73, 0x18, 0x01, 0x20, 0x03, 0x28, 0x09, 0x52, 0x06, 0x73, 0x74, 0x61, 0x74, 0x75,
	0x73, 0x22, 0x75, 0x0a, 0x1a, 0x47, 0x65, 0x74, 0x41, 0x75, 0x74, 0x68, 0x6f, 0x72, 0x69, 0x7a,
	0x65, 0x64, 0x43, 0x61, 0x72, 0x64, 0x73, 0x52, 0x65, 0x73, 0x70, 0x6f, 0x6e, 0x73, 0x65, 0x12,
	0x18, 0x0a, 0x07, 0x56, 0x65, 0x72, 0x73, 0x69, 0x6f, 0x6e, 0x18, 0x01, 0x20, 0x01, 0x28, 0x05,
	0x52, 0x07, 0x56, 0x65, 0x72, 0x73, 0x69, 0x6f, 0x6e, 0x12, 0x3d, 0x0a, 0x0f, 0x41, 0x75, 0x74,
	0x68, 0x6f, 0x72, 0x69, 0x7a, 0x65, 0x64, 0x43, 0x61, 0x72, 0x64, 0x73, 0x18, 0x02, 0x20, 0x03,
	0x28, 0x0b, 0x32, 0x13, 0x2e, 0x61, 0x70, 0x69, 0x2e, 0x41, 0x75, 0x74, 0x68, 0x6f, 0x72, 0x69,
	0x7a, 0x65, 0x64, 0x43, 0x61, 0x72, 0x64, 0x52, 0x0f, 0x41, 0x75, 0x74, 0x68, 0x6f, 0x72, 0x69,
	0x7a, 0x65, 0x64, 0x43, 0x61, 0x72, 0x64, 0x73, 0x22, 0x29, 0x0a, 0x11, 0x52, 0x65, 0x6d, 0x6f,
	0x76, 0x65, 0x43, 0x61, 0x72, 0x64, 0x52, 0x65, 0x71, 0x75, 0x65, 0x73, 0x74, 0x12, 0x14, 0x0a,
	0x05, 0x54, 0x61, 0x67, 0x49, 0x64, 0x18, 0x01, 0x20, 0x01, 0x28, 0x09, 0x52, 0x05, 0x54, 0x61,
	0x67, 0x49, 0x64, 0x22, 0x41, 0x0a, 0x12, 0x52, 0x65, 0x6d, 0x6f, 0x76, 0x65, 0x43, 0x61, 0x72,
	0x64, 0x52, 0x65, 0x73, 0x70, 0x6f, 0x6e, 0x73, 0x65, 0x12, 0x2b, 0x0a, 0x06, 0x53, 0x74, 0x61,
	0x74, 0x75, 0x73, 0x18, 0x01, 0x20, 0x01, 0x28, 0x0e, 0x32, 0x13, 0x2e, 0x61, 0x70, 0x69, 0x2e,
	0x52, 0x65, 0x73, 0x70, 0x6f, 0x6e, 0x73, 0x65, 0x53, 0x74, 0x61, 0x74, 0x75, 0x73, 0x52, 0x06,
	0x53, 0x74, 0x61, 0x74, 0x75, 0x73, 0x22, 0x58, 0x0a, 0x1c, 0x41, 0x75, 0x74, 0x68, 0x6f, 0x72,
	0x69, 0x7a, 0x61, 0x74, 0x69, 0x6f, 0x6e, 0x48, 0x69, 0x73, 0x74, 0x6f, 0x72, 0x79, 0x52, 0x65,
	0x73, 0x70, 0x6f, 0x6e, 0x73, 0x65, 0x12, 0x38, 0x0a, 0x07, 0x48, 0x69, 0x73, 0x74, 0x6f, 0x72,
	0x79, 0x18, 0x01, 0x20, 0x03, 0x28, 0x0b, 0x32, 0x1e, 0x2e, 0x61, 0x70, 0x69, 0x2e, 0x41, 0x75,
	0x74, 0x68, 0x6f, 0x72, 0x69, 0x7a, 0x61, 0x74, 0x69, 0x6f, 0x6e, 0x48, 0x69, 0x73, 0x74, 0x6f,
	0x72, 0x79, 0x45, 0x6e, 0x74, 0x72, 0x79, 0x52, 0x07, 0x48, 0x69, 0x73, 0x74, 0x6f, 0x72, 0x79,
	0x22, 0x83, 0x01, 0x0a, 0x19, 0x41, 0x75, 0x74, 0x68, 0x6f, 0x72, 0x69, 0x7a, 0x61, 0x74, 0x69,
	0x6f, 0x6e, 0x48, 0x69, 0x73, 0x74, 0x6f, 0x72, 0x79, 0x45, 0x6e, 0x74, 0x72, 0x79, 0x12, 0x38,
	0x0a, 0x09, 0x54, 0x69, 0x6d, 0x65, 0x73, 0x74, 0x61, 0x6d, 0x70, 0x18, 0x01, 0x20, 0x01, 0x28,
	0x0b, 0x32, 0x1a, 0x2e, 0x67, 0x6f, 0x6f, 0x67, 0x6c, 0x65, 0x2e, 0x70, 0x72, 0x6f, 0x74, 0x6f,
	0x62, 0x75, 0x66, 0x2e, 0x54, 0x69, 0x6d, 0x65, 0x73, 0x74, 0x61, 0x6d, 0x70, 0x52, 0x09, 0x54,
	0x69, 0x6d, 0x65, 0x73, 0x74, 0x61, 0x6d, 0x70, 0x12, 0x14, 0x0a, 0x05, 0x54, 0x61, 0x67, 0x49,
	0x64, 0x18, 0x02, 0x20, 0x01, 0x28, 0x09, 0x52, 0x05, 0x54, 0x61, 0x67, 0x49, 0x64, 0x12, 0x16,
	0x0a, 0x06, 0x53, 0x74, 0x61, 0x74, 0x75, 0x73, 0x18, 0x03, 0x20, 0x01, 0x28, 0x09, 0x52, 0x06,
	0x53, 0x74, 0x61, 0x74, 0x75, 0x73, 0x22, 0x8e, 0x01, 0x0a, 0x0e, 0x41, 0x75, 0x74, 0x68, 0x6f,
	0x72, 0x69, 0x7a, 0x65, 0x64, 0x43, 0x61, 0x72, 0x64, 0x12, 0x14, 0x0a, 0x05, 0x54, 0x61, 0x67,
	0x49, 0x64, 0x18, 0x01, 0x20, 0x01, 0x28, 0x09, 0x52, 0x05, 0x54, 0x61, 0x67, 0x49, 0x64, 0x12,
	0x16, 0x0a, 0x06, 0x53, 0x74, 0x61, 0x74, 0x75, 0x73, 0x18, 0x02, 0x20, 0x01, 0x28, 0x09, 0x52,
	0x06, 0x53, 0x74, 0x61, 0x74, 0x75, 0x73, 0x12, 0x3f, 0x0a, 0x0a, 0x45, 0x78, 0x70, 0x69, 0x72,
	0x79, 0x44, 0x61, 0x74, 0x65, 0x18, 0x03, 0x20, 0x01, 0x28, 0x0b, 0x32, 0x1a, 0x2e, 0x67, 0x6f,
	0x6f, 0x67, 0x6c, 0x65, 0x2e, 0x70, 0x72, 0x6f, 0x74, 0x6f, 0x62, 0x75, 0x66, 0x2e, 0x54, 0x69,
	0x6d, 0x65, 0x73, 0x74, 0x61, 0x6d, 0x70, 0x48, 0x00, 0x52, 0x0a, 0x45, 0x78, 0x70, 0x69, 0x72,
	0x79, 0x44, 0x61, 0x74, 0x65, 0x88, 0x01, 0x01, 0x42, 0x0d, 0x0a, 0x0b, 0x5f, 0x45, 0x78, 0x70,
	0x69, 0x72, 0x79, 0x44, 0x61, 0x74, 0x65, 0x32, 0xd2, 0x02, 0x0a, 0x03, 0x54, 0x61, 0x67, 0x12,
	0x4f, 0x0a, 0x12, 0x47, 0x65, 0x74, 0x41, 0x75, 0x74, 0x68, 0x6f, 0x72, 0x69, 0x7a, 0x65, 0x64,
	0x43, 0x61, 0x72, 0x64, 0x73, 0x12, 0x16, 0x2e, 0x67, 0x6f, 0x6f, 0x67, 0x6c, 0x65, 0x2e, 0x70,
	0x72, 0x6f, 0x74, 0x6f, 0x62, 0x75, 0x66, 0x2e, 0x45, 0x6d, 0x70, 0x74, 0x79, 0x1a, 0x1f, 0x2e,
	0x61, 0x70, 0x69, 0x2e, 0x47, 0x65, 0x74, 0x41, 0x75, 0x74, 0x68, 0x6f, 0x72, 0x69, 0x7a, 0x65,
	0x64, 0x43, 0x61, 0x72, 0x64, 0x73, 0x52, 0x65, 0x73, 0x70, 0x6f, 0x6e, 0x73, 0x65, 0x22, 0x00,
	0x12, 0x57, 0x0a, 0x12, 0x41, 0x64, 0x64, 0x41, 0x75, 0x74, 0x68, 0x6f, 0x72, 0x69, 0x7a, 0x65,
	0x64, 0x43, 0x61, 0x72, 0x64, 0x73, 0x12, 0x1e, 0x2e, 0x61, 0x70, 0x69, 0x2e, 0x41, 0x64, 0x64,
	0x41, 0x75, 0x74, 0x68, 0x6f, 0x72, 0x69, 0x7a, 0x65, 0x64, 0x43, 0x61, 0x72, 0x64, 0x73, 0x52,
	0x65, 0x71, 0x75, 0x65, 0x73, 0x74, 0x1a, 0x1f, 0x2e, 0x61, 0x70, 0x69, 0x2e, 0x41, 0x64, 0x64,
	0x41, 0x75, 0x74, 0x68, 0x6f, 0x72, 0x69, 0x7a, 0x65, 0x64, 0x43, 0x61, 0x72, 0x64, 0x73, 0x52,
	0x65, 0x73, 0x70, 0x6f, 0x6e, 0x73, 0x65, 0x22, 0x00, 0x12, 0x49, 0x0a, 0x14, 0x52, 0x65, 0x6d,
	0x6f, 0x76, 0x65, 0x41, 0x75, 0x74, 0x68, 0x6f, 0x72, 0x69, 0x7a, 0x65, 0x64, 0x43, 0x61, 0x72,
	0x64, 0x12, 0x16, 0x2e, 0x61, 0x70, 0x69, 0x2e, 0x52, 0x65, 0x6d, 0x6f, 0x76, 0x65, 0x43, 0x61,
	0x72, 0x64, 0x52, 0x65, 0x71, 0x75, 0x65, 0x73, 0x74, 0x1a, 0x17, 0x2e, 0x61, 0x70, 0x69, 0x2e,
	0x52, 0x65, 0x6d, 0x6f, 0x76, 0x65, 0x43, 0x61, 0x72, 0x64, 0x52, 0x65, 0x73, 0x70, 0x6f, 0x6e,
	0x73, 0x65, 0x22, 0x00, 0x12, 0x56, 0x0a, 0x17, 0x47, 0x65, 0x74, 0x41, 0x75, 0x74, 0x68, 0x6f,
	0x72, 0x69, 0x7a, 0x61, 0x74, 0x69, 0x6f, 0x6e, 0x48, 0x69, 0x73, 0x74, 0x6f, 0x72, 0x79, 0x12,
	0x16, 0x2e, 0x67, 0x6f, 0x6f, 0x67, 0x6c, 0x65, 0x2e, 0x70, 0x72, 0x6f, 0x74, 0x6f, 0x62, 0x75,
	0x66, 0x2e, 0x45, 0x6d, 0x70, 0x74, 0x79, 0x1a, 0x21, 0x2e, 0x61, 0x70, 0x69, 0x2e, 0x41, 0x75,
	0x74, 0x68, 0x6f, 0x72, 0x69, 0x7a, 0x61, 0x74, 0x69, 0x6f, 0x6e, 0x48, 0x69, 0x73, 0x74, 0x6f,
	0x72, 0x79, 0x52, 0x65, 0x73, 0x70, 0x6f, 0x6e, 0x73, 0x65, 0x22, 0x00, 0x42, 0x33, 0x5a, 0x31,
	0x67, 0x69, 0x74, 0x68, 0x75, 0x62, 0x2e, 0x63, 0x6f, 0x6d, 0x2f, 0x43, 0x68, 0x61, 0x72, 0x67,
	0x65, 0x50, 0x69, 0x2f, 0x43, 0x68, 0x61, 0x72, 0x67, 0x65, 0x50, 0x69, 0x2d, 0x67, 0x6f, 0x2f,
	0x70, 0x6b, 0x67, 0x2f, 0x70, 0x72, 0x6f, 0x74, 0x6f, 0x2f, 0x76, 0x31, 0x2f, 0x67, 0x72, 0x70,
	0x63, 0x62, 0x06, 0x70, 0x72, 0x6f, 0x74, 0x6f, 0x33,
}

var (
	file_tag_api_proto_rawDescOnce sync.Once
	file_tag_api_proto_rawDescData = file_tag_api_proto_rawDesc
)

func file_tag_api_proto_rawDescGZIP() []byte {
	file_tag_api_proto_rawDescOnce.Do(func() {
		file_tag_api_proto_rawDescData = protoimpl.X.CompressGZIP(file_tag_api_proto_rawDescData)
	})
	return file_tag_api_proto_rawDescData
}

var file_tag_api_proto_msgTypes = make([]protoimpl.MessageInfo, 8)
var file_tag_api_proto_goTypes = []any{
	(*AddAuthorizedCardsRequest)(nil),    // 0: api.AddAuthorizedCardsRequest
	(*AddAuthorizedCardsResponse)(nil),   // 1: api.AddAuthorizedCardsResponse
	(*GetAuthorizedCardsResponse)(nil),   // 2: api.GetAuthorizedCardsResponse
	(*RemoveCardRequest)(nil),            // 3: api.RemoveCardRequest
	(*RemoveCardResponse)(nil),           // 4: api.RemoveCardResponse
	(*AuthorizationHistoryResponse)(nil), // 5: api.AuthorizationHistoryResponse
	(*AuthorizationHistoryEntry)(nil),    // 6: api.AuthorizationHistoryEntry
	(*AuthorizedCard)(nil),               // 7: api.AuthorizedCard
	(ResponseStatus)(0),                  // 8: api.ResponseStatus
	(*timestamppb.Timestamp)(nil),        // 9: google.protobuf.Timestamp
	(*emptypb.Empty)(nil),                // 10: google.protobuf.Empty
}
var file_tag_api_proto_depIdxs = []int32{
	7,  // 0: api.AddAuthorizedCardsRequest.AuthorizedCards:type_name -> api.AuthorizedCard
	7,  // 1: api.GetAuthorizedCardsResponse.AuthorizedCards:type_name -> api.AuthorizedCard
	8,  // 2: api.RemoveCardResponse.Status:type_name -> api.ResponseStatus
	6,  // 3: api.AuthorizationHistoryResponse.History:type_name -> api.AuthorizationHistoryEntry
	9,  // 4: api.AuthorizationHistoryEntry.Timestamp:type_name -> google.protobuf.Timestamp
	9,  // 5: api.AuthorizedCard.ExpiryDate:type_name -> google.protobuf.Timestamp
	10, // 6: api.Tag.GetAuthorizedCards:input_type -> google.protobuf.Empty
	0,  // 7: api.Tag.AddAuthorizedCards:input_type -> api.AddAuthorizedCardsRequest
	3,  // 8: api.Tag.RemoveAuthorizedCard:input_type -> api.RemoveCardRequest
	10, // 9: api.Tag.GetAuthorizationHistory:input_type -> google.protobuf.Empty
	2,  // 10: api.Tag.GetAuthorizedCards:output_type -> api.GetAuthorizedCardsResponse
	1,  // 11: api.Tag.AddAuthorizedCards:output_type -> api.AddAuthorizedCardsResponse
	4,  // 12: api.Tag.RemoveAuthorizedCard:output_type -> api.RemoveCardResponse
	5,  // 13: api.Tag.GetAuthorizationHistory:output_type -> api.AuthorizationHistoryResponse
	10, // [10:14] is the sub-list for method output_type
	6,  // [6:10] is the sub-list for method input_type
	6,  // [6:6] is the sub-list for extension type_name
	6,  // [6:6] is the sub-list for extension extendee
	0,  // [0:6] is the sub-list for field type_name
}

func init() { file_tag_api_proto_init() }
func file_tag_api_proto_init() {
	if File_tag_api_proto != nil {
		return
	}
	file_enums_proto_init()
	if !protoimpl.UnsafeEnabled {
		file_tag_api_proto_msgTypes[0].Exporter = func(v any, i int) any {
			switch v := v.(*AddAuthorizedCardsRequest); i {
			case 0:
				return &v.state
			case 1:
				return &v.sizeCache
			case 2:
				return &v.unknownFields
			default:
				return nil
			}
		}
		file_tag_api_proto_msgTypes[1].Exporter = func(v any, i int) any {
			switch v := v.(*AddAuthorizedCardsResponse); i {
			case 0:
				return &v.state
			case 1:
				return &v.sizeCache
			case 2:
				return &v.unknownFields
			default:
				return nil
			}
		}
		file_tag_api_proto_msgTypes[2].Exporter = func(v any, i int) any {
			switch v := v.(*GetAuthorizedCardsResponse); i {
			case 0:
				return &v.state
			case 1:
				return &v.sizeCache
			case 2:
				return &v.unknownFields
			default:
				return nil
			}
		}
		file_tag_api_proto_msgTypes[3].Exporter = func(v any, i int) any {
			switch v := v.(*RemoveCardRequest); i {
			case 0:
				return &v.state
			case 1:
				return &v.sizeCache
			case 2:
				return &v.unknownFields
			default:
				return nil
			}
		}
		file_tag_api_proto_msgTypes[4].Exporter = func(v any, i int) any {
			switch v := v.(*RemoveCardResponse); i {
			case 0:
				return &v.state
			case 1:
				return &v.sizeCache
			case 2:
				return &v.unknownFields
			default:
				return nil
			}
		}
		file_tag_api_proto_msgTypes[5].Exporter = func(v any, i int) any {
			switch v := v.(*AuthorizationHistoryResponse); i {
			case 0:
				return &v.state
			case 1:
				return &v.sizeCache
			case 2:
				return &v.unknownFields
			default:
				return nil
			}
		}
		file_tag_api_proto_msgTypes[6].Exporter = func(v any, i int) any {
			switch v := v.(*AuthorizationHistoryEntry); i {
			case 0:
				return &v.state
			case 1:
				return &v.sizeCache
			case 2:
				return &v.unknownFields
			default:
				return nil
			}
		}
		file_tag_api_proto_msgTypes[7].Exporter = func(v any, i int) any {
			switch v := v.(*AuthorizedCard); i {
			case 0:
				return &v.state
			case 1:
				return &v.sizeCache
			case 2:
				return &v.unknownFields
			default:
				return nil
			}
		}
	}
	file_tag_api_proto_msgTypes[7].OneofWrappers = []any{}
	type x struct{}
	out := protoimpl.TypeBuilder{
		File: protoimpl.DescBuilder{
			GoPackagePath: reflect.TypeOf(x{}).PkgPath(),
			RawDescriptor: file_tag_api_proto_rawDesc,
			NumEnums:      0,
			NumMessages:   8,
			NumExtensions: 0,
			NumServices:   1,
		},
		GoTypes:           file_tag_api_proto_goTypes,
		DependencyIndexes: file_tag_api_proto_depIdxs,
		MessageInfos:      file_tag_api_proto_msgTypes,
	}.Build()
	File_tag_api_proto = out.File
	file_tag_api_proto_rawDesc = nil
	file_tag_api_proto_goTypes = nil
	file_tag_api_proto_depIdxs = nil
}
