version: '3.7'
services:
  steve-db:
    image: jsurf/rpi-mariadb # Raspberry Pi MariaDB image
    volumes:
      - db:/var/lib/mysql
    labels:
      - "com.centurylinklabs.watchtower.enable=true"
    environment:
      MYSQL_ROOT_PASSWORD: steve
      MYSQL_DATABASE: stevedb
      MYSQL_USER: steve
      MYSQL_PASSWORD: changeme
      TZ: Europe/London
    networks:
      ocpp_network:
        ipv4_address: 172.0.1.120
  steve:
    build:
      dockerfile: ./build/SteVe/Steve.Dockerfile
      context: ..
    volumes:
      - ./steve:/code
      - maven:/root/.m2 # persisting dependencies to prevent downloading them each time
    labels:
      - "com.centurylinklabs.watchtower.enable=false"
    depends_on:
      - steve-db
    links:
      - "steve-db:mariadb"
    ports:
      - "8180:8180" # expose HTTP endpoint
      - "8443:8443" # expose HTTPS endpoint
      - "9000:9000"
    networks:
      ocpp_network:
        ipv4_address: 172.0.1.12
volumes:
  maven:
  db:
networks:
  ocpp_network:
    ipam:
      config:
        - subnet: 172.0.1.0/24