// Code generated by mockery v2.43.2. DO NOT EDIT.

package mocks

import (
	ocpp_v16 "github.com/ChargePi/ocppManager-go/ocpp_v16"
	mock "github.com/stretchr/testify/mock"
)

// MockOcppConfigurationRepository is an autogenerated mock type for the OcppConfigurationRepository type
type MockOcppConfigurationRepository struct {
	mock.Mock
}

type MockOcppConfigurationRepository_Expecter struct {
	mock *mock.Mock
}

func (_m *MockOcppConfigurationRepository) EXPECT() *MockOcppConfigurationRepository_Expecter {
	return &MockOcppConfigurationRepository_Expecter{mock: &_m.Mock}
}

// GeLatestOcppConfiguration provides a mock function with given fields:
func (_m *MockOcppConfigurationRepository) GeLatestOcppConfiguration() (*ocpp_v16.Config, error) {
	ret := _m.Called()

	if len(ret) == 0 {
		panic("no return value specified for GeLatestOcppConfiguration")
	}

	var r0 *ocpp_v16.Config
	var r1 error
	if rf, ok := ret.Get(0).(func() (*ocpp_v16.Config, error)); ok {
		return rf()
	}
	if rf, ok := ret.Get(0).(func() *ocpp_v16.Config); ok {
		r0 = rf()
	} else {
		if ret.Get(0) != nil {
			r0 = ret.Get(0).(*ocpp_v16.Config)
		}
	}

	if rf, ok := ret.Get(1).(func() error); ok {
		r1 = rf()
	} else {
		r1 = ret.Error(1)
	}

	return r0, r1
}

// MockOcppConfigurationRepository_GeLatestOcppConfiguration_Call is a *mock.Call that shadows Run/Return methods with type explicit version for method 'GeLatestOcppConfiguration'
type MockOcppConfigurationRepository_GeLatestOcppConfiguration_Call struct {
	*mock.Call
}

// GeLatestOcppConfiguration is a helper method to define mock.On call
func (_e *MockOcppConfigurationRepository_Expecter) GeLatestOcppConfiguration() *MockOcppConfigurationRepository_GeLatestOcppConfiguration_Call {
	return &MockOcppConfigurationRepository_GeLatestOcppConfiguration_Call{Call: _e.mock.On("GeLatestOcppConfiguration")}
}

func (_c *MockOcppConfigurationRepository_GeLatestOcppConfiguration_Call) Run(run func()) *MockOcppConfigurationRepository_GeLatestOcppConfiguration_Call {
	_c.Call.Run(func(args mock.Arguments) {
		run()
	})
	return _c
}

func (_c *MockOcppConfigurationRepository_GeLatestOcppConfiguration_Call) Return(_a0 *ocpp_v16.Config, _a1 error) *MockOcppConfigurationRepository_GeLatestOcppConfiguration_Call {
	_c.Call.Return(_a0, _a1)
	return _c
}

func (_c *MockOcppConfigurationRepository_GeLatestOcppConfiguration_Call) RunAndReturn(run func() (*ocpp_v16.Config, error)) *MockOcppConfigurationRepository_GeLatestOcppConfiguration_Call {
	_c.Call.Return(run)
	return _c
}

// GetOcppConfiguration provides a mock function with given fields: version
func (_m *MockOcppConfigurationRepository) GetOcppConfiguration(version int) (*ocpp_v16.Config, error) {
	ret := _m.Called(version)

	if len(ret) == 0 {
		panic("no return value specified for GetOcppConfiguration")
	}

	var r0 *ocpp_v16.Config
	var r1 error
	if rf, ok := ret.Get(0).(func(int) (*ocpp_v16.Config, error)); ok {
		return rf(version)
	}
	if rf, ok := ret.Get(0).(func(int) *ocpp_v16.Config); ok {
		r0 = rf(version)
	} else {
		if ret.Get(0) != nil {
			r0 = ret.Get(0).(*ocpp_v16.Config)
		}
	}

	if rf, ok := ret.Get(1).(func(int) error); ok {
		r1 = rf(version)
	} else {
		r1 = ret.Error(1)
	}

	return r0, r1
}

// MockOcppConfigurationRepository_GetOcppConfiguration_Call is a *mock.Call that shadows Run/Return methods with type explicit version for method 'GetOcppConfiguration'
type MockOcppConfigurationRepository_GetOcppConfiguration_Call struct {
	*mock.Call
}

// GetOcppConfiguration is a helper method to define mock.On call
//   - version int
func (_e *MockOcppConfigurationRepository_Expecter) GetOcppConfiguration(version interface{}) *MockOcppConfigurationRepository_GetOcppConfiguration_Call {
	return &MockOcppConfigurationRepository_GetOcppConfiguration_Call{Call: _e.mock.On("GetOcppConfiguration", version)}
}

func (_c *MockOcppConfigurationRepository_GetOcppConfiguration_Call) Run(run func(version int)) *MockOcppConfigurationRepository_GetOcppConfiguration_Call {
	_c.Call.Run(func(args mock.Arguments) {
		run(args[0].(int))
	})
	return _c
}

func (_c *MockOcppConfigurationRepository_GetOcppConfiguration_Call) Return(_a0 *ocpp_v16.Config, _a1 error) *MockOcppConfigurationRepository_GetOcppConfiguration_Call {
	_c.Call.Return(_a0, _a1)
	return _c
}

func (_c *MockOcppConfigurationRepository_GetOcppConfiguration_Call) RunAndReturn(run func(int) (*ocpp_v16.Config, error)) *MockOcppConfigurationRepository_GetOcppConfiguration_Call {
	_c.Call.Return(run)
	return _c
}

// SetOcppConfiguration provides a mock function with given fields: _a0
func (_m *MockOcppConfigurationRepository) SetOcppConfiguration(_a0 ocpp_v16.Config) error {
	ret := _m.Called(_a0)

	if len(ret) == 0 {
		panic("no return value specified for SetOcppConfiguration")
	}

	var r0 error
	if rf, ok := ret.Get(0).(func(ocpp_v16.Config) error); ok {
		r0 = rf(_a0)
	} else {
		r0 = ret.Error(0)
	}

	return r0
}

// MockOcppConfigurationRepository_SetOcppConfiguration_Call is a *mock.Call that shadows Run/Return methods with type explicit version for method 'SetOcppConfiguration'
type MockOcppConfigurationRepository_SetOcppConfiguration_Call struct {
	*mock.Call
}

// SetOcppConfiguration is a helper method to define mock.On call
//   - _a0 ocpp_v16.Config
func (_e *MockOcppConfigurationRepository_Expecter) SetOcppConfiguration(_a0 interface{}) *MockOcppConfigurationRepository_SetOcppConfiguration_Call {
	return &MockOcppConfigurationRepository_SetOcppConfiguration_Call{Call: _e.mock.On("SetOcppConfiguration", _a0)}
}

func (_c *MockOcppConfigurationRepository_SetOcppConfiguration_Call) Run(run func(_a0 ocpp_v16.Config)) *MockOcppConfigurationRepository_SetOcppConfiguration_Call {
	_c.Call.Run(func(args mock.Arguments) {
		run(args[0].(ocpp_v16.Config))
	})
	return _c
}

func (_c *MockOcppConfigurationRepository_SetOcppConfiguration_Call) Return(_a0 error) *MockOcppConfigurationRepository_SetOcppConfiguration_Call {
	_c.Call.Return(_a0)
	return _c
}

func (_c *MockOcppConfigurationRepository_SetOcppConfiguration_Call) RunAndReturn(run func(ocpp_v16.Config) error) *MockOcppConfigurationRepository_SetOcppConfiguration_Call {
	_c.Call.Return(run)
	return _c
}

// NewMockOcppConfigurationRepository creates a new instance of MockOcppConfigurationRepository. It also registers a testing interface on the mock and a cleanup function to assert the mocks expectations.
// The first argument is typically a *testing.T value.
func NewMockOcppConfigurationRepository(t interface {
	mock.TestingT
	Cleanup(func())
}) *MockOcppConfigurationRepository {
	mock := &MockOcppConfigurationRepository{}
	mock.Mock.Test(t)

	t.Cleanup(func() { mock.AssertExpectations(t) })

	return mock
}
