// Code generated by mockery v2.43.2. DO NOT EDIT.

package mocks

import (
	context "context"

	evcc "github.com/ChargePi/ChargePi-go/pkg/hardware/evcc"
	core "github.com/lorenzodonini/ocpp-go/ocpp1.6/core"

	evse "github.com/ChargePi/ChargePi-go/internal/evse"

	mock "github.com/stretchr/testify/mock"

	notifications "github.com/ChargePi/ChargePi-go/internal/pkg/notifications"

	powerMeter "github.com/ChargePi/ChargePi-go/pkg/hardware/power-meter"

	types "github.com/lorenzodonini/ocpp-go/ocpp1.6/types"
)

// MockEVSE is an autogenerated mock type for the EVSE type
type MockEVSE struct {
	mock.Mock
}

type MockEVSE_Expecter struct {
	mock *mock.Mock
}

func (_m *MockEVSE) EXPECT() *MockEVSE_Expecter {
	return &MockEVSE_Expecter{mock: &_m.Mock}
}

// AddConnector provides a mock function with given fields: connector
func (_m *MockEVSE) AddConnector(connector evse.ConnectorSettings) error {
	ret := _m.Called(connector)

	if len(ret) == 0 {
		panic("no return value specified for AddConnector")
	}

	var r0 error
	if rf, ok := ret.Get(0).(func(evse.ConnectorSettings) error); ok {
		r0 = rf(connector)
	} else {
		r0 = ret.Error(0)
	}

	return r0
}

// MockEVSE_AddConnector_Call is a *mock.Call that shadows Run/Return methods with type explicit version for method 'AddConnector'
type MockEVSE_AddConnector_Call struct {
	*mock.Call
}

// AddConnector is a helper method to define mock.On call
//   - connector evse.ConnectorSettings
func (_e *MockEVSE_Expecter) AddConnector(connector interface{}) *MockEVSE_AddConnector_Call {
	return &MockEVSE_AddConnector_Call{Call: _e.mock.On("AddConnector", connector)}
}

func (_c *MockEVSE_AddConnector_Call) Run(run func(connector evse.ConnectorSettings)) *MockEVSE_AddConnector_Call {
	_c.Call.Run(func(args mock.Arguments) {
		run(args[0].(evse.ConnectorSettings))
	})
	return _c
}

func (_c *MockEVSE_AddConnector_Call) Return(_a0 error) *MockEVSE_AddConnector_Call {
	_c.Call.Return(_a0)
	return _c
}

func (_c *MockEVSE_AddConnector_Call) RunAndReturn(run func(evse.ConnectorSettings) error) *MockEVSE_AddConnector_Call {
	_c.Call.Return(run)
	return _c
}

// Cleanup provides a mock function with given fields:
func (_m *MockEVSE) Cleanup() error {
	ret := _m.Called()

	if len(ret) == 0 {
		panic("no return value specified for Cleanup")
	}

	var r0 error
	if rf, ok := ret.Get(0).(func() error); ok {
		r0 = rf()
	} else {
		r0 = ret.Error(0)
	}

	return r0
}

// MockEVSE_Cleanup_Call is a *mock.Call that shadows Run/Return methods with type explicit version for method 'Cleanup'
type MockEVSE_Cleanup_Call struct {
	*mock.Call
}

// Cleanup is a helper method to define mock.On call
func (_e *MockEVSE_Expecter) Cleanup() *MockEVSE_Cleanup_Call {
	return &MockEVSE_Cleanup_Call{Call: _e.mock.On("Cleanup")}
}

func (_c *MockEVSE_Cleanup_Call) Run(run func()) *MockEVSE_Cleanup_Call {
	_c.Call.Run(func(args mock.Arguments) {
		run()
	})
	return _c
}

func (_c *MockEVSE_Cleanup_Call) Return(_a0 error) *MockEVSE_Cleanup_Call {
	_c.Call.Return(_a0)
	return _c
}

func (_c *MockEVSE_Cleanup_Call) RunAndReturn(run func() error) *MockEVSE_Cleanup_Call {
	_c.Call.Return(run)
	return _c
}

// GetConnectors provides a mock function with given fields:
func (_m *MockEVSE) GetConnectors() []evse.ConnectorSettings {
	ret := _m.Called()

	if len(ret) == 0 {
		panic("no return value specified for GetConnectors")
	}

	var r0 []evse.ConnectorSettings
	if rf, ok := ret.Get(0).(func() []evse.ConnectorSettings); ok {
		r0 = rf()
	} else {
		if ret.Get(0) != nil {
			r0 = ret.Get(0).([]evse.ConnectorSettings)
		}
	}

	return r0
}

// MockEVSE_GetConnectors_Call is a *mock.Call that shadows Run/Return methods with type explicit version for method 'GetConnectors'
type MockEVSE_GetConnectors_Call struct {
	*mock.Call
}

// GetConnectors is a helper method to define mock.On call
func (_e *MockEVSE_Expecter) GetConnectors() *MockEVSE_GetConnectors_Call {
	return &MockEVSE_GetConnectors_Call{Call: _e.mock.On("GetConnectors")}
}

func (_c *MockEVSE_GetConnectors_Call) Run(run func()) *MockEVSE_GetConnectors_Call {
	_c.Call.Run(func(args mock.Arguments) {
		run()
	})
	return _c
}

func (_c *MockEVSE_GetConnectors_Call) Return(_a0 []evse.ConnectorSettings) *MockEVSE_GetConnectors_Call {
	_c.Call.Return(_a0)
	return _c
}

func (_c *MockEVSE_GetConnectors_Call) RunAndReturn(run func() []evse.ConnectorSettings) *MockEVSE_GetConnectors_Call {
	_c.Call.Return(run)
	return _c
}

// GetEvcc provides a mock function with given fields:
func (_m *MockEVSE) GetEvcc() evcc.EVCC {
	ret := _m.Called()

	if len(ret) == 0 {
		panic("no return value specified for GetEvcc")
	}

	var r0 evcc.EVCC
	if rf, ok := ret.Get(0).(func() evcc.EVCC); ok {
		r0 = rf()
	} else {
		if ret.Get(0) != nil {
			r0 = ret.Get(0).(evcc.EVCC)
		}
	}

	return r0
}

// MockEVSE_GetEvcc_Call is a *mock.Call that shadows Run/Return methods with type explicit version for method 'GetEvcc'
type MockEVSE_GetEvcc_Call struct {
	*mock.Call
}

// GetEvcc is a helper method to define mock.On call
func (_e *MockEVSE_Expecter) GetEvcc() *MockEVSE_GetEvcc_Call {
	return &MockEVSE_GetEvcc_Call{Call: _e.mock.On("GetEvcc")}
}

func (_c *MockEVSE_GetEvcc_Call) Run(run func()) *MockEVSE_GetEvcc_Call {
	_c.Call.Run(func(args mock.Arguments) {
		run()
	})
	return _c
}

func (_c *MockEVSE_GetEvcc_Call) Return(_a0 evcc.EVCC) *MockEVSE_GetEvcc_Call {
	_c.Call.Return(_a0)
	return _c
}

func (_c *MockEVSE_GetEvcc_Call) RunAndReturn(run func() evcc.EVCC) *MockEVSE_GetEvcc_Call {
	_c.Call.Return(run)
	return _c
}

// GetEvseId provides a mock function with given fields:
func (_m *MockEVSE) GetEvseId() int {
	ret := _m.Called()

	if len(ret) == 0 {
		panic("no return value specified for GetEvseId")
	}

	var r0 int
	if rf, ok := ret.Get(0).(func() int); ok {
		r0 = rf()
	} else {
		r0 = ret.Get(0).(int)
	}

	return r0
}

// MockEVSE_GetEvseId_Call is a *mock.Call that shadows Run/Return methods with type explicit version for method 'GetEvseId'
type MockEVSE_GetEvseId_Call struct {
	*mock.Call
}

// GetEvseId is a helper method to define mock.On call
func (_e *MockEVSE_Expecter) GetEvseId() *MockEVSE_GetEvseId_Call {
	return &MockEVSE_GetEvseId_Call{Call: _e.mock.On("GetEvseId")}
}

func (_c *MockEVSE_GetEvseId_Call) Run(run func()) *MockEVSE_GetEvseId_Call {
	_c.Call.Run(func(args mock.Arguments) {
		run()
	})
	return _c
}

func (_c *MockEVSE_GetEvseId_Call) Return(_a0 int) *MockEVSE_GetEvseId_Call {
	_c.Call.Return(_a0)
	return _c
}

func (_c *MockEVSE_GetEvseId_Call) RunAndReturn(run func() int) *MockEVSE_GetEvseId_Call {
	_c.Call.Return(run)
	return _c
}

// GetMaxChargingPower provides a mock function with given fields:
func (_m *MockEVSE) GetMaxChargingPower() float64 {
	ret := _m.Called()

	if len(ret) == 0 {
		panic("no return value specified for GetMaxChargingPower")
	}

	var r0 float64
	if rf, ok := ret.Get(0).(func() float64); ok {
		r0 = rf()
	} else {
		r0 = ret.Get(0).(float64)
	}

	return r0
}

// MockEVSE_GetMaxChargingPower_Call is a *mock.Call that shadows Run/Return methods with type explicit version for method 'GetMaxChargingPower'
type MockEVSE_GetMaxChargingPower_Call struct {
	*mock.Call
}

// GetMaxChargingPower is a helper method to define mock.On call
func (_e *MockEVSE_Expecter) GetMaxChargingPower() *MockEVSE_GetMaxChargingPower_Call {
	return &MockEVSE_GetMaxChargingPower_Call{Call: _e.mock.On("GetMaxChargingPower")}
}

func (_c *MockEVSE_GetMaxChargingPower_Call) Run(run func()) *MockEVSE_GetMaxChargingPower_Call {
	_c.Call.Run(func(args mock.Arguments) {
		run()
	})
	return _c
}

func (_c *MockEVSE_GetMaxChargingPower_Call) Return(_a0 float64) *MockEVSE_GetMaxChargingPower_Call {
	_c.Call.Return(_a0)
	return _c
}

func (_c *MockEVSE_GetMaxChargingPower_Call) RunAndReturn(run func() float64) *MockEVSE_GetMaxChargingPower_Call {
	_c.Call.Return(run)
	return _c
}

// GetPowerMeter provides a mock function with given fields:
func (_m *MockEVSE) GetPowerMeter() powerMeter.PowerMeter {
	ret := _m.Called()

	if len(ret) == 0 {
		panic("no return value specified for GetPowerMeter")
	}

	var r0 powerMeter.PowerMeter
	if rf, ok := ret.Get(0).(func() powerMeter.PowerMeter); ok {
		r0 = rf()
	} else {
		if ret.Get(0) != nil {
			r0 = ret.Get(0).(powerMeter.PowerMeter)
		}
	}

	return r0
}

// MockEVSE_GetPowerMeter_Call is a *mock.Call that shadows Run/Return methods with type explicit version for method 'GetPowerMeter'
type MockEVSE_GetPowerMeter_Call struct {
	*mock.Call
}

// GetPowerMeter is a helper method to define mock.On call
func (_e *MockEVSE_Expecter) GetPowerMeter() *MockEVSE_GetPowerMeter_Call {
	return &MockEVSE_GetPowerMeter_Call{Call: _e.mock.On("GetPowerMeter")}
}

func (_c *MockEVSE_GetPowerMeter_Call) Run(run func()) *MockEVSE_GetPowerMeter_Call {
	_c.Call.Run(func(args mock.Arguments) {
		run()
	})
	return _c
}

func (_c *MockEVSE_GetPowerMeter_Call) Return(_a0 powerMeter.PowerMeter) *MockEVSE_GetPowerMeter_Call {
	_c.Call.Return(_a0)
	return _c
}

func (_c *MockEVSE_GetPowerMeter_Call) RunAndReturn(run func() powerMeter.PowerMeter) *MockEVSE_GetPowerMeter_Call {
	_c.Call.Return(run)
	return _c
}

// GetStatus provides a mock function with given fields:
func (_m *MockEVSE) GetStatus() (core.ChargePointStatus, core.ChargePointErrorCode) {
	ret := _m.Called()

	if len(ret) == 0 {
		panic("no return value specified for GetStatus")
	}

	var r0 core.ChargePointStatus
	var r1 core.ChargePointErrorCode
	if rf, ok := ret.Get(0).(func() (core.ChargePointStatus, core.ChargePointErrorCode)); ok {
		return rf()
	}
	if rf, ok := ret.Get(0).(func() core.ChargePointStatus); ok {
		r0 = rf()
	} else {
		r0 = ret.Get(0).(core.ChargePointStatus)
	}

	if rf, ok := ret.Get(1).(func() core.ChargePointErrorCode); ok {
		r1 = rf()
	} else {
		r1 = ret.Get(1).(core.ChargePointErrorCode)
	}

	return r0, r1
}

// MockEVSE_GetStatus_Call is a *mock.Call that shadows Run/Return methods with type explicit version for method 'GetStatus'
type MockEVSE_GetStatus_Call struct {
	*mock.Call
}

// GetStatus is a helper method to define mock.On call
func (_e *MockEVSE_Expecter) GetStatus() *MockEVSE_GetStatus_Call {
	return &MockEVSE_GetStatus_Call{Call: _e.mock.On("GetStatus")}
}

func (_c *MockEVSE_GetStatus_Call) Run(run func()) *MockEVSE_GetStatus_Call {
	_c.Call.Run(func(args mock.Arguments) {
		run()
	})
	return _c
}

func (_c *MockEVSE_GetStatus_Call) Return(_a0 core.ChargePointStatus, _a1 core.ChargePointErrorCode) *MockEVSE_GetStatus_Call {
	_c.Call.Return(_a0, _a1)
	return _c
}

func (_c *MockEVSE_GetStatus_Call) RunAndReturn(run func() (core.ChargePointStatus, core.ChargePointErrorCode)) *MockEVSE_GetStatus_Call {
	_c.Call.Return(run)
	return _c
}

// Init provides a mock function with given fields: ctx
func (_m *MockEVSE) Init(ctx context.Context) error {
	ret := _m.Called(ctx)

	if len(ret) == 0 {
		panic("no return value specified for Init")
	}

	var r0 error
	if rf, ok := ret.Get(0).(func(context.Context) error); ok {
		r0 = rf(ctx)
	} else {
		r0 = ret.Error(0)
	}

	return r0
}

// MockEVSE_Init_Call is a *mock.Call that shadows Run/Return methods with type explicit version for method 'Init'
type MockEVSE_Init_Call struct {
	*mock.Call
}

// Init is a helper method to define mock.On call
//   - ctx context.Context
func (_e *MockEVSE_Expecter) Init(ctx interface{}) *MockEVSE_Init_Call {
	return &MockEVSE_Init_Call{Call: _e.mock.On("Init", ctx)}
}

func (_c *MockEVSE_Init_Call) Run(run func(ctx context.Context)) *MockEVSE_Init_Call {
	_c.Call.Run(func(args mock.Arguments) {
		run(args[0].(context.Context))
	})
	return _c
}

func (_c *MockEVSE_Init_Call) Return(_a0 error) *MockEVSE_Init_Call {
	_c.Call.Return(_a0)
	return _c
}

func (_c *MockEVSE_Init_Call) RunAndReturn(run func(context.Context) error) *MockEVSE_Init_Call {
	_c.Call.Return(run)
	return _c
}

// IsAvailable provides a mock function with given fields:
func (_m *MockEVSE) IsAvailable() bool {
	ret := _m.Called()

	if len(ret) == 0 {
		panic("no return value specified for IsAvailable")
	}

	var r0 bool
	if rf, ok := ret.Get(0).(func() bool); ok {
		r0 = rf()
	} else {
		r0 = ret.Get(0).(bool)
	}

	return r0
}

// MockEVSE_IsAvailable_Call is a *mock.Call that shadows Run/Return methods with type explicit version for method 'IsAvailable'
type MockEVSE_IsAvailable_Call struct {
	*mock.Call
}

// IsAvailable is a helper method to define mock.On call
func (_e *MockEVSE_Expecter) IsAvailable() *MockEVSE_IsAvailable_Call {
	return &MockEVSE_IsAvailable_Call{Call: _e.mock.On("IsAvailable")}
}

func (_c *MockEVSE_IsAvailable_Call) Run(run func()) *MockEVSE_IsAvailable_Call {
	_c.Call.Run(func(args mock.Arguments) {
		run()
	})
	return _c
}

func (_c *MockEVSE_IsAvailable_Call) Return(_a0 bool) *MockEVSE_IsAvailable_Call {
	_c.Call.Return(_a0)
	return _c
}

func (_c *MockEVSE_IsAvailable_Call) RunAndReturn(run func() bool) *MockEVSE_IsAvailable_Call {
	_c.Call.Return(run)
	return _c
}

// IsCharging provides a mock function with given fields:
func (_m *MockEVSE) IsCharging() bool {
	ret := _m.Called()

	if len(ret) == 0 {
		panic("no return value specified for IsCharging")
	}

	var r0 bool
	if rf, ok := ret.Get(0).(func() bool); ok {
		r0 = rf()
	} else {
		r0 = ret.Get(0).(bool)
	}

	return r0
}

// MockEVSE_IsCharging_Call is a *mock.Call that shadows Run/Return methods with type explicit version for method 'IsCharging'
type MockEVSE_IsCharging_Call struct {
	*mock.Call
}

// IsCharging is a helper method to define mock.On call
func (_e *MockEVSE_Expecter) IsCharging() *MockEVSE_IsCharging_Call {
	return &MockEVSE_IsCharging_Call{Call: _e.mock.On("IsCharging")}
}

func (_c *MockEVSE_IsCharging_Call) Run(run func()) *MockEVSE_IsCharging_Call {
	_c.Call.Run(func(args mock.Arguments) {
		run()
	})
	return _c
}

func (_c *MockEVSE_IsCharging_Call) Return(_a0 bool) *MockEVSE_IsCharging_Call {
	_c.Call.Return(_a0)
	return _c
}

func (_c *MockEVSE_IsCharging_Call) RunAndReturn(run func() bool) *MockEVSE_IsCharging_Call {
	_c.Call.Return(run)
	return _c
}

// IsHealthy provides a mock function with given fields:
func (_m *MockEVSE) IsHealthy() bool {
	ret := _m.Called()

	if len(ret) == 0 {
		panic("no return value specified for IsHealthy")
	}

	var r0 bool
	if rf, ok := ret.Get(0).(func() bool); ok {
		r0 = rf()
	} else {
		r0 = ret.Get(0).(bool)
	}

	return r0
}

// MockEVSE_IsHealthy_Call is a *mock.Call that shadows Run/Return methods with type explicit version for method 'IsHealthy'
type MockEVSE_IsHealthy_Call struct {
	*mock.Call
}

// IsHealthy is a helper method to define mock.On call
func (_e *MockEVSE_Expecter) IsHealthy() *MockEVSE_IsHealthy_Call {
	return &MockEVSE_IsHealthy_Call{Call: _e.mock.On("IsHealthy")}
}

func (_c *MockEVSE_IsHealthy_Call) Run(run func()) *MockEVSE_IsHealthy_Call {
	_c.Call.Run(func(args mock.Arguments) {
		run()
	})
	return _c
}

func (_c *MockEVSE_IsHealthy_Call) Return(_a0 bool) *MockEVSE_IsHealthy_Call {
	_c.Call.Return(_a0)
	return _c
}

func (_c *MockEVSE_IsHealthy_Call) RunAndReturn(run func() bool) *MockEVSE_IsHealthy_Call {
	_c.Call.Return(run)
	return _c
}

// IsPreparing provides a mock function with given fields:
func (_m *MockEVSE) IsPreparing() bool {
	ret := _m.Called()

	if len(ret) == 0 {
		panic("no return value specified for IsPreparing")
	}

	var r0 bool
	if rf, ok := ret.Get(0).(func() bool); ok {
		r0 = rf()
	} else {
		r0 = ret.Get(0).(bool)
	}

	return r0
}

// MockEVSE_IsPreparing_Call is a *mock.Call that shadows Run/Return methods with type explicit version for method 'IsPreparing'
type MockEVSE_IsPreparing_Call struct {
	*mock.Call
}

// IsPreparing is a helper method to define mock.On call
func (_e *MockEVSE_Expecter) IsPreparing() *MockEVSE_IsPreparing_Call {
	return &MockEVSE_IsPreparing_Call{Call: _e.mock.On("IsPreparing")}
}

func (_c *MockEVSE_IsPreparing_Call) Run(run func()) *MockEVSE_IsPreparing_Call {
	_c.Call.Run(func(args mock.Arguments) {
		run()
	})
	return _c
}

func (_c *MockEVSE_IsPreparing_Call) Return(_a0 bool) *MockEVSE_IsPreparing_Call {
	_c.Call.Return(_a0)
	return _c
}

func (_c *MockEVSE_IsPreparing_Call) RunAndReturn(run func() bool) *MockEVSE_IsPreparing_Call {
	_c.Call.Return(run)
	return _c
}

// IsReserved provides a mock function with given fields:
func (_m *MockEVSE) IsReserved() bool {
	ret := _m.Called()

	if len(ret) == 0 {
		panic("no return value specified for IsReserved")
	}

	var r0 bool
	if rf, ok := ret.Get(0).(func() bool); ok {
		r0 = rf()
	} else {
		r0 = ret.Get(0).(bool)
	}

	return r0
}

// MockEVSE_IsReserved_Call is a *mock.Call that shadows Run/Return methods with type explicit version for method 'IsReserved'
type MockEVSE_IsReserved_Call struct {
	*mock.Call
}

// IsReserved is a helper method to define mock.On call
func (_e *MockEVSE_Expecter) IsReserved() *MockEVSE_IsReserved_Call {
	return &MockEVSE_IsReserved_Call{Call: _e.mock.On("IsReserved")}
}

func (_c *MockEVSE_IsReserved_Call) Run(run func()) *MockEVSE_IsReserved_Call {
	_c.Call.Run(func(args mock.Arguments) {
		run()
	})
	return _c
}

func (_c *MockEVSE_IsReserved_Call) Return(_a0 bool) *MockEVSE_IsReserved_Call {
	_c.Call.Return(_a0)
	return _c
}

func (_c *MockEVSE_IsReserved_Call) RunAndReturn(run func() bool) *MockEVSE_IsReserved_Call {
	_c.Call.Return(run)
	return _c
}

// IsUnavailable provides a mock function with given fields:
func (_m *MockEVSE) IsUnavailable() bool {
	ret := _m.Called()

	if len(ret) == 0 {
		panic("no return value specified for IsUnavailable")
	}

	var r0 bool
	if rf, ok := ret.Get(0).(func() bool); ok {
		r0 = rf()
	} else {
		r0 = ret.Get(0).(bool)
	}

	return r0
}

// MockEVSE_IsUnavailable_Call is a *mock.Call that shadows Run/Return methods with type explicit version for method 'IsUnavailable'
type MockEVSE_IsUnavailable_Call struct {
	*mock.Call
}

// IsUnavailable is a helper method to define mock.On call
func (_e *MockEVSE_Expecter) IsUnavailable() *MockEVSE_IsUnavailable_Call {
	return &MockEVSE_IsUnavailable_Call{Call: _e.mock.On("IsUnavailable")}
}

func (_c *MockEVSE_IsUnavailable_Call) Run(run func()) *MockEVSE_IsUnavailable_Call {
	_c.Call.Run(func(args mock.Arguments) {
		run()
	})
	return _c
}

func (_c *MockEVSE_IsUnavailable_Call) Return(_a0 bool) *MockEVSE_IsUnavailable_Call {
	_c.Call.Return(_a0)
	return _c
}

func (_c *MockEVSE_IsUnavailable_Call) RunAndReturn(run func() bool) *MockEVSE_IsUnavailable_Call {
	_c.Call.Return(run)
	return _c
}

// Lock provides a mock function with given fields: connectorId
func (_m *MockEVSE) Lock(connectorId int) {
	_m.Called(connectorId)
}

// MockEVSE_Lock_Call is a *mock.Call that shadows Run/Return methods with type explicit version for method 'Lock'
type MockEVSE_Lock_Call struct {
	*mock.Call
}

// Lock is a helper method to define mock.On call
//   - connectorId int
func (_e *MockEVSE_Expecter) Lock(connectorId interface{}) *MockEVSE_Lock_Call {
	return &MockEVSE_Lock_Call{Call: _e.mock.On("Lock", connectorId)}
}

func (_c *MockEVSE_Lock_Call) Run(run func(connectorId int)) *MockEVSE_Lock_Call {
	_c.Call.Run(func(args mock.Arguments) {
		run(args[0].(int))
	})
	return _c
}

func (_c *MockEVSE_Lock_Call) Return() *MockEVSE_Lock_Call {
	_c.Call.Return()
	return _c
}

func (_c *MockEVSE_Lock_Call) RunAndReturn(run func(int)) *MockEVSE_Lock_Call {
	_c.Call.Return(run)
	return _c
}

// SamplePowerMeter provides a mock function with given fields: measurands
func (_m *MockEVSE) SamplePowerMeter(measurands []types.Measurand) ([]types.SampledValue, error) {
	ret := _m.Called(measurands)

	if len(ret) == 0 {
		panic("no return value specified for SamplePowerMeter")
	}

	var r0 []types.SampledValue
	var r1 error
	if rf, ok := ret.Get(0).(func([]types.Measurand) ([]types.SampledValue, error)); ok {
		return rf(measurands)
	}
	if rf, ok := ret.Get(0).(func([]types.Measurand) []types.SampledValue); ok {
		r0 = rf(measurands)
	} else {
		if ret.Get(0) != nil {
			r0 = ret.Get(0).([]types.SampledValue)
		}
	}

	if rf, ok := ret.Get(1).(func([]types.Measurand) error); ok {
		r1 = rf(measurands)
	} else {
		r1 = ret.Error(1)
	}

	return r0, r1
}

// MockEVSE_SamplePowerMeter_Call is a *mock.Call that shadows Run/Return methods with type explicit version for method 'SamplePowerMeter'
type MockEVSE_SamplePowerMeter_Call struct {
	*mock.Call
}

// SamplePowerMeter is a helper method to define mock.On call
//   - measurands []types.Measurand
func (_e *MockEVSE_Expecter) SamplePowerMeter(measurands interface{}) *MockEVSE_SamplePowerMeter_Call {
	return &MockEVSE_SamplePowerMeter_Call{Call: _e.mock.On("SamplePowerMeter", measurands)}
}

func (_c *MockEVSE_SamplePowerMeter_Call) Run(run func(measurands []types.Measurand)) *MockEVSE_SamplePowerMeter_Call {
	_c.Call.Run(func(args mock.Arguments) {
		run(args[0].([]types.Measurand))
	})
	return _c
}

func (_c *MockEVSE_SamplePowerMeter_Call) Return(_a0 []types.SampledValue, _a1 error) *MockEVSE_SamplePowerMeter_Call {
	_c.Call.Return(_a0, _a1)
	return _c
}

func (_c *MockEVSE_SamplePowerMeter_Call) RunAndReturn(run func([]types.Measurand) ([]types.SampledValue, error)) *MockEVSE_SamplePowerMeter_Call {
	_c.Call.Return(run)
	return _c
}

// SetAvailability provides a mock function with given fields: isAvailable
func (_m *MockEVSE) SetAvailability(isAvailable bool) error {
	ret := _m.Called(isAvailable)

	if len(ret) == 0 {
		panic("no return value specified for SetAvailability")
	}

	var r0 error
	if rf, ok := ret.Get(0).(func(bool) error); ok {
		r0 = rf(isAvailable)
	} else {
		r0 = ret.Error(0)
	}

	return r0
}

// MockEVSE_SetAvailability_Call is a *mock.Call that shadows Run/Return methods with type explicit version for method 'SetAvailability'
type MockEVSE_SetAvailability_Call struct {
	*mock.Call
}

// SetAvailability is a helper method to define mock.On call
//   - isAvailable bool
func (_e *MockEVSE_Expecter) SetAvailability(isAvailable interface{}) *MockEVSE_SetAvailability_Call {
	return &MockEVSE_SetAvailability_Call{Call: _e.mock.On("SetAvailability", isAvailable)}
}

func (_c *MockEVSE_SetAvailability_Call) Run(run func(isAvailable bool)) *MockEVSE_SetAvailability_Call {
	_c.Call.Run(func(args mock.Arguments) {
		run(args[0].(bool))
	})
	return _c
}

func (_c *MockEVSE_SetAvailability_Call) Return(_a0 error) *MockEVSE_SetAvailability_Call {
	_c.Call.Return(_a0)
	return _c
}

func (_c *MockEVSE_SetAvailability_Call) RunAndReturn(run func(bool) error) *MockEVSE_SetAvailability_Call {
	_c.Call.Return(run)
	return _c
}

// SetEvcc provides a mock function with given fields: _a0
func (_m *MockEVSE) SetEvcc(_a0 evcc.EVCC) error {
	ret := _m.Called(_a0)

	if len(ret) == 0 {
		panic("no return value specified for SetEvcc")
	}

	var r0 error
	if rf, ok := ret.Get(0).(func(evcc.EVCC) error); ok {
		r0 = rf(_a0)
	} else {
		r0 = ret.Error(0)
	}

	return r0
}

// MockEVSE_SetEvcc_Call is a *mock.Call that shadows Run/Return methods with type explicit version for method 'SetEvcc'
type MockEVSE_SetEvcc_Call struct {
	*mock.Call
}

// SetEvcc is a helper method to define mock.On call
//   - _a0 evcc.EVCC
func (_e *MockEVSE_Expecter) SetEvcc(_a0 interface{}) *MockEVSE_SetEvcc_Call {
	return &MockEVSE_SetEvcc_Call{Call: _e.mock.On("SetEvcc", _a0)}
}

func (_c *MockEVSE_SetEvcc_Call) Run(run func(_a0 evcc.EVCC)) *MockEVSE_SetEvcc_Call {
	_c.Call.Run(func(args mock.Arguments) {
		run(args[0].(evcc.EVCC))
	})
	return _c
}

func (_c *MockEVSE_SetEvcc_Call) Return(_a0 error) *MockEVSE_SetEvcc_Call {
	_c.Call.Return(_a0)
	return _c
}

func (_c *MockEVSE_SetEvcc_Call) RunAndReturn(run func(evcc.EVCC) error) *MockEVSE_SetEvcc_Call {
	_c.Call.Return(run)
	return _c
}

// SetMeterValuesChannel provides a mock function with given fields: notificationChannel
func (_m *MockEVSE) SetMeterValuesChannel(notificationChannel chan<- notifications.MeterValueNotification) {
	_m.Called(notificationChannel)
}

// MockEVSE_SetMeterValuesChannel_Call is a *mock.Call that shadows Run/Return methods with type explicit version for method 'SetMeterValuesChannel'
type MockEVSE_SetMeterValuesChannel_Call struct {
	*mock.Call
}

// SetMeterValuesChannel is a helper method to define mock.On call
//   - notificationChannel chan<- notifications.MeterValueNotification
func (_e *MockEVSE_Expecter) SetMeterValuesChannel(notificationChannel interface{}) *MockEVSE_SetMeterValuesChannel_Call {
	return &MockEVSE_SetMeterValuesChannel_Call{Call: _e.mock.On("SetMeterValuesChannel", notificationChannel)}
}

func (_c *MockEVSE_SetMeterValuesChannel_Call) Run(run func(notificationChannel chan<- notifications.MeterValueNotification)) *MockEVSE_SetMeterValuesChannel_Call {
	_c.Call.Run(func(args mock.Arguments) {
		run(args[0].(chan<- notifications.MeterValueNotification))
	})
	return _c
}

func (_c *MockEVSE_SetMeterValuesChannel_Call) Return() *MockEVSE_SetMeterValuesChannel_Call {
	_c.Call.Return()
	return _c
}

func (_c *MockEVSE_SetMeterValuesChannel_Call) RunAndReturn(run func(chan<- notifications.MeterValueNotification)) *MockEVSE_SetMeterValuesChannel_Call {
	_c.Call.Return(run)
	return _c
}

// SetNotificationChannel provides a mock function with given fields: notificationChannel
func (_m *MockEVSE) SetNotificationChannel(notificationChannel chan<- notifications.StatusNotification) {
	_m.Called(notificationChannel)
}

// MockEVSE_SetNotificationChannel_Call is a *mock.Call that shadows Run/Return methods with type explicit version for method 'SetNotificationChannel'
type MockEVSE_SetNotificationChannel_Call struct {
	*mock.Call
}

// SetNotificationChannel is a helper method to define mock.On call
//   - notificationChannel chan<- notifications.StatusNotification
func (_e *MockEVSE_Expecter) SetNotificationChannel(notificationChannel interface{}) *MockEVSE_SetNotificationChannel_Call {
	return &MockEVSE_SetNotificationChannel_Call{Call: _e.mock.On("SetNotificationChannel", notificationChannel)}
}

func (_c *MockEVSE_SetNotificationChannel_Call) Run(run func(notificationChannel chan<- notifications.StatusNotification)) *MockEVSE_SetNotificationChannel_Call {
	_c.Call.Run(func(args mock.Arguments) {
		run(args[0].(chan<- notifications.StatusNotification))
	})
	return _c
}

func (_c *MockEVSE_SetNotificationChannel_Call) Return() *MockEVSE_SetNotificationChannel_Call {
	_c.Call.Return()
	return _c
}

func (_c *MockEVSE_SetNotificationChannel_Call) RunAndReturn(run func(chan<- notifications.StatusNotification)) *MockEVSE_SetNotificationChannel_Call {
	_c.Call.Return(run)
	return _c
}

// SetPowerMeter provides a mock function with given fields: _a0
func (_m *MockEVSE) SetPowerMeter(_a0 powerMeter.PowerMeter) error {
	ret := _m.Called(_a0)

	if len(ret) == 0 {
		panic("no return value specified for SetPowerMeter")
	}

	var r0 error
	if rf, ok := ret.Get(0).(func(powerMeter.PowerMeter) error); ok {
		r0 = rf(_a0)
	} else {
		r0 = ret.Error(0)
	}

	return r0
}

// MockEVSE_SetPowerMeter_Call is a *mock.Call that shadows Run/Return methods with type explicit version for method 'SetPowerMeter'
type MockEVSE_SetPowerMeter_Call struct {
	*mock.Call
}

// SetPowerMeter is a helper method to define mock.On call
//   - _a0 powerMeter.PowerMeter
func (_e *MockEVSE_Expecter) SetPowerMeter(_a0 interface{}) *MockEVSE_SetPowerMeter_Call {
	return &MockEVSE_SetPowerMeter_Call{Call: _e.mock.On("SetPowerMeter", _a0)}
}

func (_c *MockEVSE_SetPowerMeter_Call) Run(run func(_a0 powerMeter.PowerMeter)) *MockEVSE_SetPowerMeter_Call {
	_c.Call.Run(func(args mock.Arguments) {
		run(args[0].(powerMeter.PowerMeter))
	})
	return _c
}

func (_c *MockEVSE_SetPowerMeter_Call) Return(_a0 error) *MockEVSE_SetPowerMeter_Call {
	_c.Call.Return(_a0)
	return _c
}

func (_c *MockEVSE_SetPowerMeter_Call) RunAndReturn(run func(powerMeter.PowerMeter) error) *MockEVSE_SetPowerMeter_Call {
	_c.Call.Return(run)
	return _c
}

// SetStatus provides a mock function with given fields: status, errCode
func (_m *MockEVSE) SetStatus(status core.ChargePointStatus, errCode core.ChargePointErrorCode) error {
	ret := _m.Called(status, errCode)

	if len(ret) == 0 {
		panic("no return value specified for SetStatus")
	}

	var r0 error
	if rf, ok := ret.Get(0).(func(core.ChargePointStatus, core.ChargePointErrorCode) error); ok {
		r0 = rf(status, errCode)
	} else {
		r0 = ret.Error(0)
	}

	return r0
}

// MockEVSE_SetStatus_Call is a *mock.Call that shadows Run/Return methods with type explicit version for method 'SetStatus'
type MockEVSE_SetStatus_Call struct {
	*mock.Call
}

// SetStatus is a helper method to define mock.On call
//   - status core.ChargePointStatus
//   - errCode core.ChargePointErrorCode
func (_e *MockEVSE_Expecter) SetStatus(status interface{}, errCode interface{}) *MockEVSE_SetStatus_Call {
	return &MockEVSE_SetStatus_Call{Call: _e.mock.On("SetStatus", status, errCode)}
}

func (_c *MockEVSE_SetStatus_Call) Run(run func(status core.ChargePointStatus, errCode core.ChargePointErrorCode)) *MockEVSE_SetStatus_Call {
	_c.Call.Run(func(args mock.Arguments) {
		run(args[0].(core.ChargePointStatus), args[1].(core.ChargePointErrorCode))
	})
	return _c
}

func (_c *MockEVSE_SetStatus_Call) Return(_a0 error) *MockEVSE_SetStatus_Call {
	_c.Call.Return(_a0)
	return _c
}

func (_c *MockEVSE_SetStatus_Call) RunAndReturn(run func(core.ChargePointStatus, core.ChargePointErrorCode) error) *MockEVSE_SetStatus_Call {
	_c.Call.Return(run)
	return _c
}

// StartCharging provides a mock function with given fields: connectorId, measurands, sampleInterval
func (_m *MockEVSE) StartCharging(connectorId *int, measurands []types.Measurand, sampleInterval string) error {
	ret := _m.Called(connectorId, measurands, sampleInterval)

	if len(ret) == 0 {
		panic("no return value specified for StartCharging")
	}

	var r0 error
	if rf, ok := ret.Get(0).(func(*int, []types.Measurand, string) error); ok {
		r0 = rf(connectorId, measurands, sampleInterval)
	} else {
		r0 = ret.Error(0)
	}

	return r0
}

// MockEVSE_StartCharging_Call is a *mock.Call that shadows Run/Return methods with type explicit version for method 'StartCharging'
type MockEVSE_StartCharging_Call struct {
	*mock.Call
}

// StartCharging is a helper method to define mock.On call
//   - connectorId *int
//   - measurands []types.Measurand
//   - sampleInterval string
func (_e *MockEVSE_Expecter) StartCharging(connectorId interface{}, measurands interface{}, sampleInterval interface{}) *MockEVSE_StartCharging_Call {
	return &MockEVSE_StartCharging_Call{Call: _e.mock.On("StartCharging", connectorId, measurands, sampleInterval)}
}

func (_c *MockEVSE_StartCharging_Call) Run(run func(connectorId *int, measurands []types.Measurand, sampleInterval string)) *MockEVSE_StartCharging_Call {
	_c.Call.Run(func(args mock.Arguments) {
		run(args[0].(*int), args[1].([]types.Measurand), args[2].(string))
	})
	return _c
}

func (_c *MockEVSE_StartCharging_Call) Return(_a0 error) *MockEVSE_StartCharging_Call {
	_c.Call.Return(_a0)
	return _c
}

func (_c *MockEVSE_StartCharging_Call) RunAndReturn(run func(*int, []types.Measurand, string) error) *MockEVSE_StartCharging_Call {
	_c.Call.Return(run)
	return _c
}

// StopCharging provides a mock function with given fields: reason
func (_m *MockEVSE) StopCharging(reason core.Reason) error {
	ret := _m.Called(reason)

	if len(ret) == 0 {
		panic("no return value specified for StopCharging")
	}

	var r0 error
	if rf, ok := ret.Get(0).(func(core.Reason) error); ok {
		r0 = rf(reason)
	} else {
		r0 = ret.Error(0)
	}

	return r0
}

// MockEVSE_StopCharging_Call is a *mock.Call that shadows Run/Return methods with type explicit version for method 'StopCharging'
type MockEVSE_StopCharging_Call struct {
	*mock.Call
}

// StopCharging is a helper method to define mock.On call
//   - reason core.Reason
func (_e *MockEVSE_Expecter) StopCharging(reason interface{}) *MockEVSE_StopCharging_Call {
	return &MockEVSE_StopCharging_Call{Call: _e.mock.On("StopCharging", reason)}
}

func (_c *MockEVSE_StopCharging_Call) Run(run func(reason core.Reason)) *MockEVSE_StopCharging_Call {
	_c.Call.Run(func(args mock.Arguments) {
		run(args[0].(core.Reason))
	})
	return _c
}

func (_c *MockEVSE_StopCharging_Call) Return(_a0 error) *MockEVSE_StopCharging_Call {
	_c.Call.Return(_a0)
	return _c
}

func (_c *MockEVSE_StopCharging_Call) RunAndReturn(run func(core.Reason) error) *MockEVSE_StopCharging_Call {
	_c.Call.Return(run)
	return _c
}

// Unlock provides a mock function with given fields: connectorId
func (_m *MockEVSE) Unlock(connectorId int) {
	_m.Called(connectorId)
}

// MockEVSE_Unlock_Call is a *mock.Call that shadows Run/Return methods with type explicit version for method 'Unlock'
type MockEVSE_Unlock_Call struct {
	*mock.Call
}

// Unlock is a helper method to define mock.On call
//   - connectorId int
func (_e *MockEVSE_Expecter) Unlock(connectorId interface{}) *MockEVSE_Unlock_Call {
	return &MockEVSE_Unlock_Call{Call: _e.mock.On("Unlock", connectorId)}
}

func (_c *MockEVSE_Unlock_Call) Run(run func(connectorId int)) *MockEVSE_Unlock_Call {
	_c.Call.Run(func(args mock.Arguments) {
		run(args[0].(int))
	})
	return _c
}

func (_c *MockEVSE_Unlock_Call) Return() *MockEVSE_Unlock_Call {
	_c.Call.Return()
	return _c
}

func (_c *MockEVSE_Unlock_Call) RunAndReturn(run func(int)) *MockEVSE_Unlock_Call {
	_c.Call.Return(run)
	return _c
}

// NewMockEVSE creates a new instance of MockEVSE. It also registers a testing interface on the mock and a cleanup function to assert the mocks expectations.
// The first argument is typically a *testing.T value.
func NewMockEVSE(t interface {
	mock.TestingT
	Cleanup(func())
}) *MockEVSE {
	mock := &MockEVSE{}
	mock.Mock.Test(t)

	t.Cleanup(func() { mock.AssertExpectations(t) })

	return mock
}
