// Code generated by mockery v2.43.2. DO NOT EDIT.

package mocks

import (
	context "context"

	mock "github.com/stretchr/testify/mock"

	ocpp2_0_1display "github.com/lorenzodonini/ocpp-go/ocpp2.0.1/display"
)

// MockDisplay is an autogenerated mock type for the Display type
type MockDisplay struct {
	mock.Mock
}

type MockDisplay_Expecter struct {
	mock *mock.Mock
}

func (_m *MockDisplay) EXPECT() *MockDisplay_Expecter {
	return &MockDisplay_Expecter{mock: &_m.Mock}
}

// Cleanup provides a mock function with given fields: ctx
func (_m *MockDisplay) Cleanup(ctx context.Context) error {
	ret := _m.Called(ctx)

	if len(ret) == 0 {
		panic("no return value specified for Cleanup")
	}

	var r0 error
	if rf, ok := ret.Get(0).(func(context.Context) error); ok {
		r0 = rf(ctx)
	} else {
		r0 = ret.Error(0)
	}

	return r0
}

// MockDisplay_Cleanup_Call is a *mock.Call that shadows Run/Return methods with type explicit version for method 'Cleanup'
type MockDisplay_Cleanup_Call struct {
	*mock.Call
}

// Cleanup is a helper method to define mock.On call
//   - ctx context.Context
func (_e *MockDisplay_Expecter) Cleanup(ctx interface{}) *MockDisplay_Cleanup_Call {
	return &MockDisplay_Cleanup_Call{Call: _e.mock.On("Cleanup", ctx)}
}

func (_c *MockDisplay_Cleanup_Call) Run(run func(ctx context.Context)) *MockDisplay_Cleanup_Call {
	_c.Call.Run(func(args mock.Arguments) {
		run(args[0].(context.Context))
	})
	return _c
}

func (_c *MockDisplay_Cleanup_Call) Return(_a0 error) *MockDisplay_Cleanup_Call {
	_c.Call.Return(_a0)
	return _c
}

func (_c *MockDisplay_Cleanup_Call) RunAndReturn(run func(context.Context) error) *MockDisplay_Cleanup_Call {
	_c.Call.Return(run)
	return _c
}

// Clear provides a mock function with given fields:
func (_m *MockDisplay) Clear() error {
	ret := _m.Called()

	if len(ret) == 0 {
		panic("no return value specified for Clear")
	}

	var r0 error
	if rf, ok := ret.Get(0).(func() error); ok {
		r0 = rf()
	} else {
		r0 = ret.Error(0)
	}

	return r0
}

// MockDisplay_Clear_Call is a *mock.Call that shadows Run/Return methods with type explicit version for method 'Clear'
type MockDisplay_Clear_Call struct {
	*mock.Call
}

// Clear is a helper method to define mock.On call
func (_e *MockDisplay_Expecter) Clear() *MockDisplay_Clear_Call {
	return &MockDisplay_Clear_Call{Call: _e.mock.On("Clear")}
}

func (_c *MockDisplay_Clear_Call) Run(run func()) *MockDisplay_Clear_Call {
	_c.Call.Run(func(args mock.Arguments) {
		run()
	})
	return _c
}

func (_c *MockDisplay_Clear_Call) Return(_a0 error) *MockDisplay_Clear_Call {
	_c.Call.Return(_a0)
	return _c
}

func (_c *MockDisplay_Clear_Call) RunAndReturn(run func() error) *MockDisplay_Clear_Call {
	_c.Call.Return(run)
	return _c
}

// DisplayMessage provides a mock function with given fields: message
func (_m *MockDisplay) DisplayMessage(message ocpp2_0_1display.MessageInfo) error {
	ret := _m.Called(message)

	if len(ret) == 0 {
		panic("no return value specified for DisplayMessage")
	}

	var r0 error
	if rf, ok := ret.Get(0).(func(ocpp2_0_1display.MessageInfo) error); ok {
		r0 = rf(message)
	} else {
		r0 = ret.Error(0)
	}

	return r0
}

// MockDisplay_DisplayMessage_Call is a *mock.Call that shadows Run/Return methods with type explicit version for method 'DisplayMessage'
type MockDisplay_DisplayMessage_Call struct {
	*mock.Call
}

// DisplayMessage is a helper method to define mock.On call
//   - message ocpp2_0_1display.MessageInfo
func (_e *MockDisplay_Expecter) DisplayMessage(message interface{}) *MockDisplay_DisplayMessage_Call {
	return &MockDisplay_DisplayMessage_Call{Call: _e.mock.On("DisplayMessage", message)}
}

func (_c *MockDisplay_DisplayMessage_Call) Run(run func(message ocpp2_0_1display.MessageInfo)) *MockDisplay_DisplayMessage_Call {
	_c.Call.Run(func(args mock.Arguments) {
		run(args[0].(ocpp2_0_1display.MessageInfo))
	})
	return _c
}

func (_c *MockDisplay_DisplayMessage_Call) Return(_a0 error) *MockDisplay_DisplayMessage_Call {
	_c.Call.Return(_a0)
	return _c
}

func (_c *MockDisplay_DisplayMessage_Call) RunAndReturn(run func(ocpp2_0_1display.MessageInfo) error) *MockDisplay_DisplayMessage_Call {
	_c.Call.Return(run)
	return _c
}

// GetType provides a mock function with given fields:
func (_m *MockDisplay) GetType() string {
	ret := _m.Called()

	if len(ret) == 0 {
		panic("no return value specified for GetType")
	}

	var r0 string
	if rf, ok := ret.Get(0).(func() string); ok {
		r0 = rf()
	} else {
		r0 = ret.Get(0).(string)
	}

	return r0
}

// MockDisplay_GetType_Call is a *mock.Call that shadows Run/Return methods with type explicit version for method 'GetType'
type MockDisplay_GetType_Call struct {
	*mock.Call
}

// GetType is a helper method to define mock.On call
func (_e *MockDisplay_Expecter) GetType() *MockDisplay_GetType_Call {
	return &MockDisplay_GetType_Call{Call: _e.mock.On("GetType")}
}

func (_c *MockDisplay_GetType_Call) Run(run func()) *MockDisplay_GetType_Call {
	_c.Call.Run(func(args mock.Arguments) {
		run()
	})
	return _c
}

func (_c *MockDisplay_GetType_Call) Return(_a0 string) *MockDisplay_GetType_Call {
	_c.Call.Return(_a0)
	return _c
}

func (_c *MockDisplay_GetType_Call) RunAndReturn(run func() string) *MockDisplay_GetType_Call {
	_c.Call.Return(run)
	return _c
}

// NewMockDisplay creates a new instance of MockDisplay. It also registers a testing interface on the mock and a cleanup function to assert the mocks expectations.
// The first argument is typically a *testing.T value.
func NewMockDisplay(t interface {
	mock.TestingT
	Cleanup(func())
}) *MockDisplay {
	mock := &MockDisplay{}
	mock.Mock.Test(t)

	t.Cleanup(func() { mock.AssertExpectations(t) })

	return mock
}
