// Code generated by mockery v2.43.2. DO NOT EDIT.

package mocks

import (
	mock "github.com/stretchr/testify/mock"

	types "github.com/lorenzodonini/ocpp-go/ocpp1.6/types"
)

// MockChargingScheduleRepository is an autogenerated mock type for the ChargingScheduleRepository type
type MockChargingScheduleRepository struct {
	mock.Mock
}

type MockChargingScheduleRepository_Expecter struct {
	mock *mock.Mock
}

func (_m *MockChargingScheduleRepository) EXPECT() *MockChargingScheduleRepository_Expecter {
	return &MockChargingScheduleRepository_Expecter{mock: &_m.Mock}
}

// AddProfile provides a mock function with given fields: profile
func (_m *MockChargingScheduleRepository) AddProfile(profile *types.ChargingProfile) error {
	ret := _m.Called(profile)

	if len(ret) == 0 {
		panic("no return value specified for AddProfile")
	}

	var r0 error
	if rf, ok := ret.Get(0).(func(*types.ChargingProfile) error); ok {
		r0 = rf(profile)
	} else {
		r0 = ret.Error(0)
	}

	return r0
}

// MockChargingScheduleRepository_AddProfile_Call is a *mock.Call that shadows Run/Return methods with type explicit version for method 'AddProfile'
type MockChargingScheduleRepository_AddProfile_Call struct {
	*mock.Call
}

// AddProfile is a helper method to define mock.On call
//   - profile *types.ChargingProfile
func (_e *MockChargingScheduleRepository_Expecter) AddProfile(profile interface{}) *MockChargingScheduleRepository_AddProfile_Call {
	return &MockChargingScheduleRepository_AddProfile_Call{Call: _e.mock.On("AddProfile", profile)}
}

func (_c *MockChargingScheduleRepository_AddProfile_Call) Run(run func(profile *types.ChargingProfile)) *MockChargingScheduleRepository_AddProfile_Call {
	_c.Call.Run(func(args mock.Arguments) {
		run(args[0].(*types.ChargingProfile))
	})
	return _c
}

func (_c *MockChargingScheduleRepository_AddProfile_Call) Return(_a0 error) *MockChargingScheduleRepository_AddProfile_Call {
	_c.Call.Return(_a0)
	return _c
}

func (_c *MockChargingScheduleRepository_AddProfile_Call) RunAndReturn(run func(*types.ChargingProfile) error) *MockChargingScheduleRepository_AddProfile_Call {
	_c.Call.Return(run)
	return _c
}

// GetProfile provides a mock function with given fields: profileId
func (_m *MockChargingScheduleRepository) GetProfile(profileId int) (*types.ChargingProfile, error) {
	ret := _m.Called(profileId)

	if len(ret) == 0 {
		panic("no return value specified for GetProfile")
	}

	var r0 *types.ChargingProfile
	var r1 error
	if rf, ok := ret.Get(0).(func(int) (*types.ChargingProfile, error)); ok {
		return rf(profileId)
	}
	if rf, ok := ret.Get(0).(func(int) *types.ChargingProfile); ok {
		r0 = rf(profileId)
	} else {
		if ret.Get(0) != nil {
			r0 = ret.Get(0).(*types.ChargingProfile)
		}
	}

	if rf, ok := ret.Get(1).(func(int) error); ok {
		r1 = rf(profileId)
	} else {
		r1 = ret.Error(1)
	}

	return r0, r1
}

// MockChargingScheduleRepository_GetProfile_Call is a *mock.Call that shadows Run/Return methods with type explicit version for method 'GetProfile'
type MockChargingScheduleRepository_GetProfile_Call struct {
	*mock.Call
}

// GetProfile is a helper method to define mock.On call
//   - profileId int
func (_e *MockChargingScheduleRepository_Expecter) GetProfile(profileId interface{}) *MockChargingScheduleRepository_GetProfile_Call {
	return &MockChargingScheduleRepository_GetProfile_Call{Call: _e.mock.On("GetProfile", profileId)}
}

func (_c *MockChargingScheduleRepository_GetProfile_Call) Run(run func(profileId int)) *MockChargingScheduleRepository_GetProfile_Call {
	_c.Call.Run(func(args mock.Arguments) {
		run(args[0].(int))
	})
	return _c
}

func (_c *MockChargingScheduleRepository_GetProfile_Call) Return(_a0 *types.ChargingProfile, _a1 error) *MockChargingScheduleRepository_GetProfile_Call {
	_c.Call.Return(_a0, _a1)
	return _c
}

func (_c *MockChargingScheduleRepository_GetProfile_Call) RunAndReturn(run func(int) (*types.ChargingProfile, error)) *MockChargingScheduleRepository_GetProfile_Call {
	_c.Call.Return(run)
	return _c
}

// GetProfiles provides a mock function with given fields:
func (_m *MockChargingScheduleRepository) GetProfiles() ([]types.ChargingProfile, error) {
	ret := _m.Called()

	if len(ret) == 0 {
		panic("no return value specified for GetProfiles")
	}

	var r0 []types.ChargingProfile
	var r1 error
	if rf, ok := ret.Get(0).(func() ([]types.ChargingProfile, error)); ok {
		return rf()
	}
	if rf, ok := ret.Get(0).(func() []types.ChargingProfile); ok {
		r0 = rf()
	} else {
		if ret.Get(0) != nil {
			r0 = ret.Get(0).([]types.ChargingProfile)
		}
	}

	if rf, ok := ret.Get(1).(func() error); ok {
		r1 = rf()
	} else {
		r1 = ret.Error(1)
	}

	return r0, r1
}

// MockChargingScheduleRepository_GetProfiles_Call is a *mock.Call that shadows Run/Return methods with type explicit version for method 'GetProfiles'
type MockChargingScheduleRepository_GetProfiles_Call struct {
	*mock.Call
}

// GetProfiles is a helper method to define mock.On call
func (_e *MockChargingScheduleRepository_Expecter) GetProfiles() *MockChargingScheduleRepository_GetProfiles_Call {
	return &MockChargingScheduleRepository_GetProfiles_Call{Call: _e.mock.On("GetProfiles")}
}

func (_c *MockChargingScheduleRepository_GetProfiles_Call) Run(run func()) *MockChargingScheduleRepository_GetProfiles_Call {
	_c.Call.Run(func(args mock.Arguments) {
		run()
	})
	return _c
}

func (_c *MockChargingScheduleRepository_GetProfiles_Call) Return(_a0 []types.ChargingProfile, _a1 error) *MockChargingScheduleRepository_GetProfiles_Call {
	_c.Call.Return(_a0, _a1)
	return _c
}

func (_c *MockChargingScheduleRepository_GetProfiles_Call) RunAndReturn(run func() ([]types.ChargingProfile, error)) *MockChargingScheduleRepository_GetProfiles_Call {
	_c.Call.Return(run)
	return _c
}

// RemoveProfile provides a mock function with given fields: profileId
func (_m *MockChargingScheduleRepository) RemoveProfile(profileId int) error {
	ret := _m.Called(profileId)

	if len(ret) == 0 {
		panic("no return value specified for RemoveProfile")
	}

	var r0 error
	if rf, ok := ret.Get(0).(func(int) error); ok {
		r0 = rf(profileId)
	} else {
		r0 = ret.Error(0)
	}

	return r0
}

// MockChargingScheduleRepository_RemoveProfile_Call is a *mock.Call that shadows Run/Return methods with type explicit version for method 'RemoveProfile'
type MockChargingScheduleRepository_RemoveProfile_Call struct {
	*mock.Call
}

// RemoveProfile is a helper method to define mock.On call
//   - profileId int
func (_e *MockChargingScheduleRepository_Expecter) RemoveProfile(profileId interface{}) *MockChargingScheduleRepository_RemoveProfile_Call {
	return &MockChargingScheduleRepository_RemoveProfile_Call{Call: _e.mock.On("RemoveProfile", profileId)}
}

func (_c *MockChargingScheduleRepository_RemoveProfile_Call) Run(run func(profileId int)) *MockChargingScheduleRepository_RemoveProfile_Call {
	_c.Call.Run(func(args mock.Arguments) {
		run(args[0].(int))
	})
	return _c
}

func (_c *MockChargingScheduleRepository_RemoveProfile_Call) Return(_a0 error) *MockChargingScheduleRepository_RemoveProfile_Call {
	_c.Call.Return(_a0)
	return _c
}

func (_c *MockChargingScheduleRepository_RemoveProfile_Call) RunAndReturn(run func(int) error) *MockChargingScheduleRepository_RemoveProfile_Call {
	_c.Call.Return(run)
	return _c
}

// NewMockChargingScheduleRepository creates a new instance of MockChargingScheduleRepository. It also registers a testing interface on the mock and a cleanup function to assert the mocks expectations.
// The first argument is typically a *testing.T value.
func NewMockChargingScheduleRepository(t interface {
	mock.TestingT
	Cleanup(func())
}) *MockChargingScheduleRepository {
	mock := &MockChargingScheduleRepository{}
	mock.Mock.Test(t)

	t.Cleanup(func() { mock.AssertExpectations(t) })

	return mock
}
