version: '3.7'
services:
  chargepi:
    build:
      dockerfile: ../../build/package/Dockerfile
      context: ../..
      target: chargepi
    restart: always
    volumes:
      - ./configs/:/ChargePi/configs/
    devices:
      - /dev/ttyAMA0:/dev/ttyAMA0
      - /dev/mem:/dev/mem
    privileged: true