version: '3.7'
services:
  chargepi:
    build:
      dockerfile: ../../build/Dockerfile
      context: ../..
      target: chargepi
    restart: always
    volumes:
      - data:/tmp/chargepi
    devices:
      - /dev/ttyAMA0:/dev/ttyAMA0
      - /dev/mem:/dev/mem
    privileged: true
volumes:
  data: