// Code generated by mockery v2.43.2. DO NOT EDIT.

package mocks

import (
	types "github.com/lorenzodonini/ocpp-go/ocpp1.6/types"
	mock "github.com/stretchr/testify/mock"
)

// MockTagRepository is an autogenerated mock type for the TagRepository type
type MockTagRepository struct {
	mock.Mock
}

type MockTagRepository_Expecter struct {
	mock *mock.Mock
}

func (_m *MockTagRepository) EXPECT() *MockTagRepository_Expecter {
	return &MockTagRepository_Expecter{mock: &_m.Mock}
}

// AddTag provides a mock function with given fields: tagId, tagInfo
func (_m *MockTagRepository) AddTag(tagId string, tagInfo *types.IdTagInfo) error {
	ret := _m.Called(tagId, tagInfo)

	if len(ret) == 0 {
		panic("no return value specified for AddTag")
	}

	var r0 error
	if rf, ok := ret.Get(0).(func(string, *types.IdTagInfo) error); ok {
		r0 = rf(tagId, tagInfo)
	} else {
		r0 = ret.Error(0)
	}

	return r0
}

// MockTagRepository_AddTag_Call is a *mock.Call that shadows Run/Return methods with type explicit version for method 'AddTag'
type MockTagRepository_AddTag_Call struct {
	*mock.Call
}

// AddTag is a helper method to define mock.On call
//   - tagId string
//   - tagInfo *types.IdTagInfo
func (_e *MockTagRepository_Expecter) AddTag(tagId interface{}, tagInfo interface{}) *MockTagRepository_AddTag_Call {
	return &MockTagRepository_AddTag_Call{Call: _e.mock.On("AddTag", tagId, tagInfo)}
}

func (_c *MockTagRepository_AddTag_Call) Run(run func(tagId string, tagInfo *types.IdTagInfo)) *MockTagRepository_AddTag_Call {
	_c.Call.Run(func(args mock.Arguments) {
		run(args[0].(string), args[1].(*types.IdTagInfo))
	})
	return _c
}

func (_c *MockTagRepository_AddTag_Call) Return(_a0 error) *MockTagRepository_AddTag_Call {
	_c.Call.Return(_a0)
	return _c
}

func (_c *MockTagRepository_AddTag_Call) RunAndReturn(run func(string, *types.IdTagInfo) error) *MockTagRepository_AddTag_Call {
	_c.Call.Return(run)
	return _c
}

// GetTag provides a mock function with given fields: tagId
func (_m *MockTagRepository) GetTag(tagId string) (*types.IdTagInfo, error) {
	ret := _m.Called(tagId)

	if len(ret) == 0 {
		panic("no return value specified for GetTag")
	}

	var r0 *types.IdTagInfo
	var r1 error
	if rf, ok := ret.Get(0).(func(string) (*types.IdTagInfo, error)); ok {
		return rf(tagId)
	}
	if rf, ok := ret.Get(0).(func(string) *types.IdTagInfo); ok {
		r0 = rf(tagId)
	} else {
		if ret.Get(0) != nil {
			r0 = ret.Get(0).(*types.IdTagInfo)
		}
	}

	if rf, ok := ret.Get(1).(func(string) error); ok {
		r1 = rf(tagId)
	} else {
		r1 = ret.Error(1)
	}

	return r0, r1
}

// MockTagRepository_GetTag_Call is a *mock.Call that shadows Run/Return methods with type explicit version for method 'GetTag'
type MockTagRepository_GetTag_Call struct {
	*mock.Call
}

// GetTag is a helper method to define mock.On call
//   - tagId string
func (_e *MockTagRepository_Expecter) GetTag(tagId interface{}) *MockTagRepository_GetTag_Call {
	return &MockTagRepository_GetTag_Call{Call: _e.mock.On("GetTag", tagId)}
}

func (_c *MockTagRepository_GetTag_Call) Run(run func(tagId string)) *MockTagRepository_GetTag_Call {
	_c.Call.Run(func(args mock.Arguments) {
		run(args[0].(string))
	})
	return _c
}

func (_c *MockTagRepository_GetTag_Call) Return(_a0 *types.IdTagInfo, _a1 error) *MockTagRepository_GetTag_Call {
	_c.Call.Return(_a0, _a1)
	return _c
}

func (_c *MockTagRepository_GetTag_Call) RunAndReturn(run func(string) (*types.IdTagInfo, error)) *MockTagRepository_GetTag_Call {
	_c.Call.Return(run)
	return _c
}

// GetTags provides a mock function with given fields:
func (_m *MockTagRepository) GetTags() ([]*types.IdTagInfo, error) {
	ret := _m.Called()

	if len(ret) == 0 {
		panic("no return value specified for GetTags")
	}

	var r0 []*types.IdTagInfo
	var r1 error
	if rf, ok := ret.Get(0).(func() ([]*types.IdTagInfo, error)); ok {
		return rf()
	}
	if rf, ok := ret.Get(0).(func() []*types.IdTagInfo); ok {
		r0 = rf()
	} else {
		if ret.Get(0) != nil {
			r0 = ret.Get(0).([]*types.IdTagInfo)
		}
	}

	if rf, ok := ret.Get(1).(func() error); ok {
		r1 = rf()
	} else {
		r1 = ret.Error(1)
	}

	return r0, r1
}

// MockTagRepository_GetTags_Call is a *mock.Call that shadows Run/Return methods with type explicit version for method 'GetTags'
type MockTagRepository_GetTags_Call struct {
	*mock.Call
}

// GetTags is a helper method to define mock.On call
func (_e *MockTagRepository_Expecter) GetTags() *MockTagRepository_GetTags_Call {
	return &MockTagRepository_GetTags_Call{Call: _e.mock.On("GetTags")}
}

func (_c *MockTagRepository_GetTags_Call) Run(run func()) *MockTagRepository_GetTags_Call {
	_c.Call.Run(func(args mock.Arguments) {
		run()
	})
	return _c
}

func (_c *MockTagRepository_GetTags_Call) Return(_a0 []*types.IdTagInfo, _a1 error) *MockTagRepository_GetTags_Call {
	_c.Call.Return(_a0, _a1)
	return _c
}

func (_c *MockTagRepository_GetTags_Call) RunAndReturn(run func() ([]*types.IdTagInfo, error)) *MockTagRepository_GetTags_Call {
	_c.Call.Return(run)
	return _c
}

// RemoveTag provides a mock function with given fields: tagId
func (_m *MockTagRepository) RemoveTag(tagId string) error {
	ret := _m.Called(tagId)

	if len(ret) == 0 {
		panic("no return value specified for RemoveTag")
	}

	var r0 error
	if rf, ok := ret.Get(0).(func(string) error); ok {
		r0 = rf(tagId)
	} else {
		r0 = ret.Error(0)
	}

	return r0
}

// MockTagRepository_RemoveTag_Call is a *mock.Call that shadows Run/Return methods with type explicit version for method 'RemoveTag'
type MockTagRepository_RemoveTag_Call struct {
	*mock.Call
}

// RemoveTag is a helper method to define mock.On call
//   - tagId string
func (_e *MockTagRepository_Expecter) RemoveTag(tagId interface{}) *MockTagRepository_RemoveTag_Call {
	return &MockTagRepository_RemoveTag_Call{Call: _e.mock.On("RemoveTag", tagId)}
}

func (_c *MockTagRepository_RemoveTag_Call) Run(run func(tagId string)) *MockTagRepository_RemoveTag_Call {
	_c.Call.Run(func(args mock.Arguments) {
		run(args[0].(string))
	})
	return _c
}

func (_c *MockTagRepository_RemoveTag_Call) Return(_a0 error) *MockTagRepository_RemoveTag_Call {
	_c.Call.Return(_a0)
	return _c
}

func (_c *MockTagRepository_RemoveTag_Call) RunAndReturn(run func(string) error) *MockTagRepository_RemoveTag_Call {
	_c.Call.Return(run)
	return _c
}

// RemoveTags provides a mock function with given fields:
func (_m *MockTagRepository) RemoveTags() error {
	ret := _m.Called()

	if len(ret) == 0 {
		panic("no return value specified for RemoveTags")
	}

	var r0 error
	if rf, ok := ret.Get(0).(func() error); ok {
		r0 = rf()
	} else {
		r0 = ret.Error(0)
	}

	return r0
}

// MockTagRepository_RemoveTags_Call is a *mock.Call that shadows Run/Return methods with type explicit version for method 'RemoveTags'
type MockTagRepository_RemoveTags_Call struct {
	*mock.Call
}

// RemoveTags is a helper method to define mock.On call
func (_e *MockTagRepository_Expecter) RemoveTags() *MockTagRepository_RemoveTags_Call {
	return &MockTagRepository_RemoveTags_Call{Call: _e.mock.On("RemoveTags")}
}

func (_c *MockTagRepository_RemoveTags_Call) Run(run func()) *MockTagRepository_RemoveTags_Call {
	_c.Call.Run(func(args mock.Arguments) {
		run()
	})
	return _c
}

func (_c *MockTagRepository_RemoveTags_Call) Return(_a0 error) *MockTagRepository_RemoveTags_Call {
	_c.Call.Return(_a0)
	return _c
}

func (_c *MockTagRepository_RemoveTags_Call) RunAndReturn(run func() error) *MockTagRepository_RemoveTags_Call {
	_c.Call.Return(run)
	return _c
}

// NewMockTagRepository creates a new instance of MockTagRepository. It also registers a testing interface on the mock and a cleanup function to assert the mocks expectations.
// The first argument is typically a *testing.T value.
func NewMockTagRepository(t interface {
	mock.TestingT
	Cleanup(func())
}) *MockTagRepository {
	mock := &MockTagRepository{}
	mock.Mock.Test(t)

	t.Cleanup(func() { mock.AssertExpectations(t) })

	return mock
}
