// Code generated by mockery v2.43.2. DO NOT EDIT.

package mocks

import (
	smartCharging "github.com/ChargePi/ChargePi-go/internal/smart-charging"
	types "github.com/lorenzodonini/ocpp-go/ocpp1.6/types"
	mock "github.com/stretchr/testify/mock"
)

// MockSmartChargingManager is an autogenerated mock type for the Manager type
type MockSmartChargingManager struct {
	mock.Mock
}

type MockSmartChargingManager_Expecter struct {
	mock *mock.Mock
}

func (_m *MockSmartChargingManager) EXPECT() *MockSmartChargingManager_Expecter {
	return &MockSmartChargingManager_Expecter{mock: &_m.Mock}
}

// AddProfile provides a mock function with given fields: profile
func (_m *MockSmartChargingManager) AddProfile(profile *types.ChargingProfile) error {
	ret := _m.Called(profile)

	if len(ret) == 0 {
		panic("no return value specified for AddProfile")
	}

	var r0 error
	if rf, ok := ret.Get(0).(func(*types.ChargingProfile) error); ok {
		r0 = rf(profile)
	} else {
		r0 = ret.Error(0)
	}

	return r0
}

// MockSmartChargingManager_AddProfile_Call is a *mock.Call that shadows Run/Return methods with type explicit version for method 'AddProfile'
type MockSmartChargingManager_AddProfile_Call struct {
	*mock.Call
}

// AddProfile is a helper method to define mock.On call
//   - profile *types.ChargingProfile
func (_e *MockSmartChargingManager_Expecter) AddProfile(profile interface{}) *MockSmartChargingManager_AddProfile_Call {
	return &MockSmartChargingManager_AddProfile_Call{Call: _e.mock.On("AddProfile", profile)}
}

func (_c *MockSmartChargingManager_AddProfile_Call) Run(run func(profile *types.ChargingProfile)) *MockSmartChargingManager_AddProfile_Call {
	_c.Call.Run(func(args mock.Arguments) {
		run(args[0].(*types.ChargingProfile))
	})
	return _c
}

func (_c *MockSmartChargingManager_AddProfile_Call) Return(_a0 error) *MockSmartChargingManager_AddProfile_Call {
	_c.Call.Return(_a0)
	return _c
}

func (_c *MockSmartChargingManager_AddProfile_Call) RunAndReturn(run func(*types.ChargingProfile) error) *MockSmartChargingManager_AddProfile_Call {
	_c.Call.Return(run)
	return _c
}

// GetCompositeSchedule provides a mock function with given fields:
func (_m *MockSmartChargingManager) GetCompositeSchedule() []smartCharging.ScheduleInterval {
	ret := _m.Called()

	if len(ret) == 0 {
		panic("no return value specified for GetCompositeSchedule")
	}

	var r0 []smartCharging.ScheduleInterval
	if rf, ok := ret.Get(0).(func() []smartCharging.ScheduleInterval); ok {
		r0 = rf()
	} else {
		if ret.Get(0) != nil {
			r0 = ret.Get(0).([]smartCharging.ScheduleInterval)
		}
	}

	return r0
}

// MockSmartChargingManager_GetCompositeSchedule_Call is a *mock.Call that shadows Run/Return methods with type explicit version for method 'GetCompositeSchedule'
type MockSmartChargingManager_GetCompositeSchedule_Call struct {
	*mock.Call
}

// GetCompositeSchedule is a helper method to define mock.On call
func (_e *MockSmartChargingManager_Expecter) GetCompositeSchedule() *MockSmartChargingManager_GetCompositeSchedule_Call {
	return &MockSmartChargingManager_GetCompositeSchedule_Call{Call: _e.mock.On("GetCompositeSchedule")}
}

func (_c *MockSmartChargingManager_GetCompositeSchedule_Call) Run(run func()) *MockSmartChargingManager_GetCompositeSchedule_Call {
	_c.Call.Run(func(args mock.Arguments) {
		run()
	})
	return _c
}

func (_c *MockSmartChargingManager_GetCompositeSchedule_Call) Return(_a0 []smartCharging.ScheduleInterval) *MockSmartChargingManager_GetCompositeSchedule_Call {
	_c.Call.Return(_a0)
	return _c
}

func (_c *MockSmartChargingManager_GetCompositeSchedule_Call) RunAndReturn(run func() []smartCharging.ScheduleInterval) *MockSmartChargingManager_GetCompositeSchedule_Call {
	_c.Call.Return(run)
	return _c
}

// GetProfile provides a mock function with given fields: profileId
func (_m *MockSmartChargingManager) GetProfile(profileId int) (*types.ChargingProfile, error) {
	ret := _m.Called(profileId)

	if len(ret) == 0 {
		panic("no return value specified for GetProfile")
	}

	var r0 *types.ChargingProfile
	var r1 error
	if rf, ok := ret.Get(0).(func(int) (*types.ChargingProfile, error)); ok {
		return rf(profileId)
	}
	if rf, ok := ret.Get(0).(func(int) *types.ChargingProfile); ok {
		r0 = rf(profileId)
	} else {
		if ret.Get(0) != nil {
			r0 = ret.Get(0).(*types.ChargingProfile)
		}
	}

	if rf, ok := ret.Get(1).(func(int) error); ok {
		r1 = rf(profileId)
	} else {
		r1 = ret.Error(1)
	}

	return r0, r1
}

// MockSmartChargingManager_GetProfile_Call is a *mock.Call that shadows Run/Return methods with type explicit version for method 'GetProfile'
type MockSmartChargingManager_GetProfile_Call struct {
	*mock.Call
}

// GetProfile is a helper method to define mock.On call
//   - profileId int
func (_e *MockSmartChargingManager_Expecter) GetProfile(profileId interface{}) *MockSmartChargingManager_GetProfile_Call {
	return &MockSmartChargingManager_GetProfile_Call{Call: _e.mock.On("GetProfile", profileId)}
}

func (_c *MockSmartChargingManager_GetProfile_Call) Run(run func(profileId int)) *MockSmartChargingManager_GetProfile_Call {
	_c.Call.Run(func(args mock.Arguments) {
		run(args[0].(int))
	})
	return _c
}

func (_c *MockSmartChargingManager_GetProfile_Call) Return(_a0 *types.ChargingProfile, _a1 error) *MockSmartChargingManager_GetProfile_Call {
	_c.Call.Return(_a0, _a1)
	return _c
}

func (_c *MockSmartChargingManager_GetProfile_Call) RunAndReturn(run func(int) (*types.ChargingProfile, error)) *MockSmartChargingManager_GetProfile_Call {
	_c.Call.Return(run)
	return _c
}

// GetProfiles provides a mock function with given fields:
func (_m *MockSmartChargingManager) GetProfiles() []types.ChargingProfile {
	ret := _m.Called()

	if len(ret) == 0 {
		panic("no return value specified for GetProfiles")
	}

	var r0 []types.ChargingProfile
	if rf, ok := ret.Get(0).(func() []types.ChargingProfile); ok {
		r0 = rf()
	} else {
		if ret.Get(0) != nil {
			r0 = ret.Get(0).([]types.ChargingProfile)
		}
	}

	return r0
}

// MockSmartChargingManager_GetProfiles_Call is a *mock.Call that shadows Run/Return methods with type explicit version for method 'GetProfiles'
type MockSmartChargingManager_GetProfiles_Call struct {
	*mock.Call
}

// GetProfiles is a helper method to define mock.On call
func (_e *MockSmartChargingManager_Expecter) GetProfiles() *MockSmartChargingManager_GetProfiles_Call {
	return &MockSmartChargingManager_GetProfiles_Call{Call: _e.mock.On("GetProfiles")}
}

func (_c *MockSmartChargingManager_GetProfiles_Call) Run(run func()) *MockSmartChargingManager_GetProfiles_Call {
	_c.Call.Run(func(args mock.Arguments) {
		run()
	})
	return _c
}

func (_c *MockSmartChargingManager_GetProfiles_Call) Return(_a0 []types.ChargingProfile) *MockSmartChargingManager_GetProfiles_Call {
	_c.Call.Return(_a0)
	return _c
}

func (_c *MockSmartChargingManager_GetProfiles_Call) RunAndReturn(run func() []types.ChargingProfile) *MockSmartChargingManager_GetProfiles_Call {
	_c.Call.Return(run)
	return _c
}

// RemoveProfile provides a mock function with given fields: profileId
func (_m *MockSmartChargingManager) RemoveProfile(profileId int) error {
	ret := _m.Called(profileId)

	if len(ret) == 0 {
		panic("no return value specified for RemoveProfile")
	}

	var r0 error
	if rf, ok := ret.Get(0).(func(int) error); ok {
		r0 = rf(profileId)
	} else {
		r0 = ret.Error(0)
	}

	return r0
}

// MockSmartChargingManager_RemoveProfile_Call is a *mock.Call that shadows Run/Return methods with type explicit version for method 'RemoveProfile'
type MockSmartChargingManager_RemoveProfile_Call struct {
	*mock.Call
}

// RemoveProfile is a helper method to define mock.On call
//   - profileId int
func (_e *MockSmartChargingManager_Expecter) RemoveProfile(profileId interface{}) *MockSmartChargingManager_RemoveProfile_Call {
	return &MockSmartChargingManager_RemoveProfile_Call{Call: _e.mock.On("RemoveProfile", profileId)}
}

func (_c *MockSmartChargingManager_RemoveProfile_Call) Run(run func(profileId int)) *MockSmartChargingManager_RemoveProfile_Call {
	_c.Call.Run(func(args mock.Arguments) {
		run(args[0].(int))
	})
	return _c
}

func (_c *MockSmartChargingManager_RemoveProfile_Call) Return(_a0 error) *MockSmartChargingManager_RemoveProfile_Call {
	_c.Call.Return(_a0)
	return _c
}

func (_c *MockSmartChargingManager_RemoveProfile_Call) RunAndReturn(run func(int) error) *MockSmartChargingManager_RemoveProfile_Call {
	_c.Call.Return(run)
	return _c
}

// NewMockSmartChargingManager creates a new instance of MockSmartChargingManager. It also registers a testing interface on the mock and a cleanup function to assert the mocks expectations.
// The first argument is typically a *testing.T value.
func NewMockSmartChargingManager(t interface {
	mock.TestingT
	Cleanup(func())
}) *MockSmartChargingManager {
	mock := &MockSmartChargingManager{}
	mock.Mock.Test(t)

	t.Cleanup(func() { mock.AssertExpectations(t) })

	return mock
}
