// Code generated by mockery v2.43.2. DO NOT EDIT.

package mocks

import (
	context "context"

	mock "github.com/stretchr/testify/mock"
)

// Mockuploader is an autogenerated mock type for the uploader type
type Mockuploader struct {
	mock.Mock
}

type Mockuploader_Expecter struct {
	mock *mock.Mock
}

func (_m *Mockuploader) EXPECT() *Mockuploader_Expecter {
	return &Mockuploader_Expecter{mock: &_m.Mock}
}

// Upload provides a mock function with given fields: _a0, bytes, location
func (_m *Mockuploader) Upload(_a0 context.Context, bytes []byte, location string) error {
	ret := _m.Called(_a0, bytes, location)

	if len(ret) == 0 {
		panic("no return value specified for Upload")
	}

	var r0 error
	if rf, ok := ret.Get(0).(func(context.Context, []byte, string) error); ok {
		r0 = rf(_a0, bytes, location)
	} else {
		r0 = ret.Error(0)
	}

	return r0
}

// Mockuploader_Upload_Call is a *mock.Call that shadows Run/Return methods with type explicit version for method 'Upload'
type Mockuploader_Upload_Call struct {
	*mock.Call
}

// Upload is a helper method to define mock.On call
//   - _a0 context.Context
//   - bytes []byte
//   - location string
func (_e *Mockuploader_Expecter) Upload(_a0 interface{}, bytes interface{}, location interface{}) *Mockuploader_Upload_Call {
	return &Mockuploader_Upload_Call{Call: _e.mock.On("Upload", _a0, bytes, location)}
}

func (_c *Mockuploader_Upload_Call) Run(run func(_a0 context.Context, bytes []byte, location string)) *Mockuploader_Upload_Call {
	_c.Call.Run(func(args mock.Arguments) {
		run(args[0].(context.Context), args[1].([]byte), args[2].(string))
	})
	return _c
}

func (_c *Mockuploader_Upload_Call) Return(_a0 error) *Mockuploader_Upload_Call {
	_c.Call.Return(_a0)
	return _c
}

func (_c *Mockuploader_Upload_Call) RunAndReturn(run func(context.Context, []byte, string) error) *Mockuploader_Upload_Call {
	_c.Call.Return(run)
	return _c
}

// NewMockuploader creates a new instance of Mockuploader. It also registers a testing interface on the mock and a cleanup function to assert the mocks expectations.
// The first argument is typically a *testing.T value.
func NewMockuploader(t interface {
	mock.TestingT
	Cleanup(func())
}) *Mockuploader {
	mock := &Mockuploader{}
	mock.Mock.Test(t)

	t.Cleanup(func() { mock.AssertExpectations(t) })

	return mock
}
