// Code generated by mockery v2.43.2. DO NOT EDIT.

package mocks

import (
	indicator "github.com/ChargePi/ChargePi-go/pkg/hardware/indicator"
	mock "github.com/stretchr/testify/mock"
)

// MockIndicator is an autogenerated mock type for the Indicator type
type MockIndicator struct {
	mock.Mock
}

type MockIndicator_Expecter struct {
	mock *mock.Mock
}

func (_m *MockIndicator) EXPECT() *MockIndicator_Expecter {
	return &MockIndicator_Expecter{mock: &_m.Mock}
}

// Blink provides a mock function with given fields: index, times, color
func (_m *MockIndicator) Blink(index int, times int, color indicator.Color) error {
	ret := _m.Called(index, times, color)

	if len(ret) == 0 {
		panic("no return value specified for Blink")
	}

	var r0 error
	if rf, ok := ret.Get(0).(func(int, int, indicator.Color) error); ok {
		r0 = rf(index, times, color)
	} else {
		r0 = ret.Error(0)
	}

	return r0
}

// MockIndicator_Blink_Call is a *mock.Call that shadows Run/Return methods with type explicit version for method 'Blink'
type MockIndicator_Blink_Call struct {
	*mock.Call
}

// Blink is a helper method to define mock.On call
//   - index int
//   - times int
//   - color indicator.Color
func (_e *MockIndicator_Expecter) Blink(index interface{}, times interface{}, color interface{}) *MockIndicator_Blink_Call {
	return &MockIndicator_Blink_Call{Call: _e.mock.On("Blink", index, times, color)}
}

func (_c *MockIndicator_Blink_Call) Run(run func(index int, times int, color indicator.Color)) *MockIndicator_Blink_Call {
	_c.Call.Run(func(args mock.Arguments) {
		run(args[0].(int), args[1].(int), args[2].(indicator.Color))
	})
	return _c
}

func (_c *MockIndicator_Blink_Call) Return(_a0 error) *MockIndicator_Blink_Call {
	_c.Call.Return(_a0)
	return _c
}

func (_c *MockIndicator_Blink_Call) RunAndReturn(run func(int, int, indicator.Color) error) *MockIndicator_Blink_Call {
	_c.Call.Return(run)
	return _c
}

// ChangeColor provides a mock function with given fields: index, color
func (_m *MockIndicator) ChangeColor(index int, color indicator.Color) error {
	ret := _m.Called(index, color)

	if len(ret) == 0 {
		panic("no return value specified for ChangeColor")
	}

	var r0 error
	if rf, ok := ret.Get(0).(func(int, indicator.Color) error); ok {
		r0 = rf(index, color)
	} else {
		r0 = ret.Error(0)
	}

	return r0
}

// MockIndicator_ChangeColor_Call is a *mock.Call that shadows Run/Return methods with type explicit version for method 'ChangeColor'
type MockIndicator_ChangeColor_Call struct {
	*mock.Call
}

// ChangeColor is a helper method to define mock.On call
//   - index int
//   - color indicator.Color
func (_e *MockIndicator_Expecter) ChangeColor(index interface{}, color interface{}) *MockIndicator_ChangeColor_Call {
	return &MockIndicator_ChangeColor_Call{Call: _e.mock.On("ChangeColor", index, color)}
}

func (_c *MockIndicator_ChangeColor_Call) Run(run func(index int, color indicator.Color)) *MockIndicator_ChangeColor_Call {
	_c.Call.Run(func(args mock.Arguments) {
		run(args[0].(int), args[1].(indicator.Color))
	})
	return _c
}

func (_c *MockIndicator_ChangeColor_Call) Return(_a0 error) *MockIndicator_ChangeColor_Call {
	_c.Call.Return(_a0)
	return _c
}

func (_c *MockIndicator_ChangeColor_Call) RunAndReturn(run func(int, indicator.Color) error) *MockIndicator_ChangeColor_Call {
	_c.Call.Return(run)
	return _c
}

// Cleanup provides a mock function with given fields:
func (_m *MockIndicator) Cleanup() {
	_m.Called()
}

// MockIndicator_Cleanup_Call is a *mock.Call that shadows Run/Return methods with type explicit version for method 'Cleanup'
type MockIndicator_Cleanup_Call struct {
	*mock.Call
}

// Cleanup is a helper method to define mock.On call
func (_e *MockIndicator_Expecter) Cleanup() *MockIndicator_Cleanup_Call {
	return &MockIndicator_Cleanup_Call{Call: _e.mock.On("Cleanup")}
}

func (_c *MockIndicator_Cleanup_Call) Run(run func()) *MockIndicator_Cleanup_Call {
	_c.Call.Run(func(args mock.Arguments) {
		run()
	})
	return _c
}

func (_c *MockIndicator_Cleanup_Call) Return() *MockIndicator_Cleanup_Call {
	_c.Call.Return()
	return _c
}

func (_c *MockIndicator_Cleanup_Call) RunAndReturn(run func()) *MockIndicator_Cleanup_Call {
	_c.Call.Return(run)
	return _c
}

// GetBrightness provides a mock function with given fields:
func (_m *MockIndicator) GetBrightness() int {
	ret := _m.Called()

	if len(ret) == 0 {
		panic("no return value specified for GetBrightness")
	}

	var r0 int
	if rf, ok := ret.Get(0).(func() int); ok {
		r0 = rf()
	} else {
		r0 = ret.Get(0).(int)
	}

	return r0
}

// MockIndicator_GetBrightness_Call is a *mock.Call that shadows Run/Return methods with type explicit version for method 'GetBrightness'
type MockIndicator_GetBrightness_Call struct {
	*mock.Call
}

// GetBrightness is a helper method to define mock.On call
func (_e *MockIndicator_Expecter) GetBrightness() *MockIndicator_GetBrightness_Call {
	return &MockIndicator_GetBrightness_Call{Call: _e.mock.On("GetBrightness")}
}

func (_c *MockIndicator_GetBrightness_Call) Run(run func()) *MockIndicator_GetBrightness_Call {
	_c.Call.Run(func(args mock.Arguments) {
		run()
	})
	return _c
}

func (_c *MockIndicator_GetBrightness_Call) Return(_a0 int) *MockIndicator_GetBrightness_Call {
	_c.Call.Return(_a0)
	return _c
}

func (_c *MockIndicator_GetBrightness_Call) RunAndReturn(run func() int) *MockIndicator_GetBrightness_Call {
	_c.Call.Return(run)
	return _c
}

// GetType provides a mock function with given fields:
func (_m *MockIndicator) GetType() string {
	ret := _m.Called()

	if len(ret) == 0 {
		panic("no return value specified for GetType")
	}

	var r0 string
	if rf, ok := ret.Get(0).(func() string); ok {
		r0 = rf()
	} else {
		r0 = ret.Get(0).(string)
	}

	return r0
}

// MockIndicator_GetType_Call is a *mock.Call that shadows Run/Return methods with type explicit version for method 'GetType'
type MockIndicator_GetType_Call struct {
	*mock.Call
}

// GetType is a helper method to define mock.On call
func (_e *MockIndicator_Expecter) GetType() *MockIndicator_GetType_Call {
	return &MockIndicator_GetType_Call{Call: _e.mock.On("GetType")}
}

func (_c *MockIndicator_GetType_Call) Run(run func()) *MockIndicator_GetType_Call {
	_c.Call.Run(func(args mock.Arguments) {
		run()
	})
	return _c
}

func (_c *MockIndicator_GetType_Call) Return(_a0 string) *MockIndicator_GetType_Call {
	_c.Call.Return(_a0)
	return _c
}

func (_c *MockIndicator_GetType_Call) RunAndReturn(run func() string) *MockIndicator_GetType_Call {
	_c.Call.Return(run)
	return _c
}

// SetBrightness provides a mock function with given fields: brightness
func (_m *MockIndicator) SetBrightness(brightness int) error {
	ret := _m.Called(brightness)

	if len(ret) == 0 {
		panic("no return value specified for SetBrightness")
	}

	var r0 error
	if rf, ok := ret.Get(0).(func(int) error); ok {
		r0 = rf(brightness)
	} else {
		r0 = ret.Error(0)
	}

	return r0
}

// MockIndicator_SetBrightness_Call is a *mock.Call that shadows Run/Return methods with type explicit version for method 'SetBrightness'
type MockIndicator_SetBrightness_Call struct {
	*mock.Call
}

// SetBrightness is a helper method to define mock.On call
//   - brightness int
func (_e *MockIndicator_Expecter) SetBrightness(brightness interface{}) *MockIndicator_SetBrightness_Call {
	return &MockIndicator_SetBrightness_Call{Call: _e.mock.On("SetBrightness", brightness)}
}

func (_c *MockIndicator_SetBrightness_Call) Run(run func(brightness int)) *MockIndicator_SetBrightness_Call {
	_c.Call.Run(func(args mock.Arguments) {
		run(args[0].(int))
	})
	return _c
}

func (_c *MockIndicator_SetBrightness_Call) Return(_a0 error) *MockIndicator_SetBrightness_Call {
	_c.Call.Return(_a0)
	return _c
}

func (_c *MockIndicator_SetBrightness_Call) RunAndReturn(run func(int) error) *MockIndicator_SetBrightness_Call {
	_c.Call.Return(run)
	return _c
}

// NewMockIndicator creates a new instance of MockIndicator. It also registers a testing interface on the mock and a cleanup function to assert the mocks expectations.
// The first argument is typically a *testing.T value.
func NewMockIndicator(t interface {
	mock.TestingT
	Cleanup(func())
}) *MockIndicator {
	mock := &MockIndicator{}
	mock.Mock.Test(t)

	t.Cleanup(func() { mock.AssertExpectations(t) })

	return mock
}
