// Code generated by mockery v2.43.2. DO NOT EDIT.

package mocks

import (
	evse "github.com/ChargePi/ChargePi-go/internal/evse"

	mock "github.com/stretchr/testify/mock"
)

// MockEvseSettingsRepository is an autogenerated mock type for the EvseSettingsRepository type
type MockEvseSettingsRepository struct {
	mock.Mock
}

type MockEvseSettingsRepository_Expecter struct {
	mock *mock.Mock
}

func (_m *MockEvseSettingsRepository) EXPECT() *MockEvseSettingsRepository_Expecter {
	return &MockEvseSettingsRepository_Expecter{mock: &_m.Mock}
}

// GetEvseSettings provides a mock function with given fields:
func (_m *MockEvseSettingsRepository) GetEvseSettings() ([]evse.Settings, error) {
	ret := _m.Called()

	if len(ret) == 0 {
		panic("no return value specified for GetEvseSettings")
	}

	var r0 []evse.Settings
	var r1 error
	if rf, ok := ret.Get(0).(func() ([]evse.Settings, error)); ok {
		return rf()
	}
	if rf, ok := ret.Get(0).(func() []evse.Settings); ok {
		r0 = rf()
	} else {
		if ret.Get(0) != nil {
			r0 = ret.Get(0).([]evse.Settings)
		}
	}

	if rf, ok := ret.Get(1).(func() error); ok {
		r1 = rf()
	} else {
		r1 = ret.Error(1)
	}

	return r0, r1
}

// MockEvseSettingsRepository_GetEvseSettings_Call is a *mock.Call that shadows Run/Return methods with type explicit version for method 'GetEvseSettings'
type MockEvseSettingsRepository_GetEvseSettings_Call struct {
	*mock.Call
}

// GetEvseSettings is a helper method to define mock.On call
func (_e *MockEvseSettingsRepository_Expecter) GetEvseSettings() *MockEvseSettingsRepository_GetEvseSettings_Call {
	return &MockEvseSettingsRepository_GetEvseSettings_Call{Call: _e.mock.On("GetEvseSettings")}
}

func (_c *MockEvseSettingsRepository_GetEvseSettings_Call) Run(run func()) *MockEvseSettingsRepository_GetEvseSettings_Call {
	_c.Call.Run(func(args mock.Arguments) {
		run()
	})
	return _c
}

func (_c *MockEvseSettingsRepository_GetEvseSettings_Call) Return(_a0 []evse.Settings, _a1 error) *MockEvseSettingsRepository_GetEvseSettings_Call {
	_c.Call.Return(_a0, _a1)
	return _c
}

func (_c *MockEvseSettingsRepository_GetEvseSettings_Call) RunAndReturn(run func() ([]evse.Settings, error)) *MockEvseSettingsRepository_GetEvseSettings_Call {
	_c.Call.Return(run)
	return _c
}

// SetEvseSettings provides a mock function with given fields: _a0
func (_m *MockEvseSettingsRepository) SetEvseSettings(_a0 []evse.Settings) error {
	ret := _m.Called(_a0)

	if len(ret) == 0 {
		panic("no return value specified for SetEvseSettings")
	}

	var r0 error
	if rf, ok := ret.Get(0).(func([]evse.Settings) error); ok {
		r0 = rf(_a0)
	} else {
		r0 = ret.Error(0)
	}

	return r0
}

// MockEvseSettingsRepository_SetEvseSettings_Call is a *mock.Call that shadows Run/Return methods with type explicit version for method 'SetEvseSettings'
type MockEvseSettingsRepository_SetEvseSettings_Call struct {
	*mock.Call
}

// SetEvseSettings is a helper method to define mock.On call
//   - _a0 []evse.Settings
func (_e *MockEvseSettingsRepository_Expecter) SetEvseSettings(_a0 interface{}) *MockEvseSettingsRepository_SetEvseSettings_Call {
	return &MockEvseSettingsRepository_SetEvseSettings_Call{Call: _e.mock.On("SetEvseSettings", _a0)}
}

func (_c *MockEvseSettingsRepository_SetEvseSettings_Call) Run(run func(_a0 []evse.Settings)) *MockEvseSettingsRepository_SetEvseSettings_Call {
	_c.Call.Run(func(args mock.Arguments) {
		run(args[0].([]evse.Settings))
	})
	return _c
}

func (_c *MockEvseSettingsRepository_SetEvseSettings_Call) Return(_a0 error) *MockEvseSettingsRepository_SetEvseSettings_Call {
	_c.Call.Return(_a0)
	return _c
}

func (_c *MockEvseSettingsRepository_SetEvseSettings_Call) RunAndReturn(run func([]evse.Settings) error) *MockEvseSettingsRepository_SetEvseSettings_Call {
	_c.Call.Return(run)
	return _c
}

// NewMockEvseSettingsRepository creates a new instance of MockEvseSettingsRepository. It also registers a testing interface on the mock and a cleanup function to assert the mocks expectations.
// The first argument is typically a *testing.T value.
func NewMockEvseSettingsRepository(t interface {
	mock.TestingT
	Cleanup(func())
}) *MockEvseSettingsRepository {
	mock := &MockEvseSettingsRepository{}
	mock.Mock.Test(t)

	t.Cleanup(func() { mock.AssertExpectations(t) })

	return mock
}
