syntax = "proto3";

package users.v1;

service UserService {
  rpc AddUser(AddUserRequest) returns (AddUserResponse) {}
  rpc GetUsers(GetUsersRequest) returns (GetUsersResponse) {}
  rpc GetUser(GetUserRequest) returns (GetUserResponse) {}
  rpc RemoveUser(RemoveUserRequest) returns (RemoveUserResponse) {}
}


message User {
  string username = 1;
  string password = 2;
  string role = 3;
}

message AddUserRequest {
  User user = 1;
}

message AddUserResponse {
  string status = 1;
}

message GetUsersRequest {
  optional int32 page = 1; // Optional pagination parameter
  optional int32 page_size = 2; // Optional page size for pagination
  optional string username_filter = 3; // Optional filter for username
  optional string role_filter = 4; // Optional filter for user role
}

message GetUsersResponse {
  repeated User users = 1;
}

message GetUserRequest {
  string username = 1;
}

message GetUserResponse {
  User user = 1;
}

message RemoveUserRequest {
  string username = 1;
}

message RemoveUserResponse {
  string status = 1;
}
