// Code generated by mockery v2.43.2. DO NOT EDIT.

package mocks

import (
	time "time"

	mock "github.com/stretchr/testify/mock"
)

// MockDiagnosticsService is an autogenerated mock type for the Service type
type MockDiagnosticsService struct {
	mock.Mock
}

type MockDiagnosticsService_Expecter struct {
	mock *mock.Mock
}

func (_m *MockDiagnosticsService) EXPECT() *MockDiagnosticsService_Expecter {
	return &MockDiagnosticsService_Expecter{mock: &_m.Mock}
}

// GetLogs provides a mock function with given fields:
func (_m *MockDiagnosticsService) GetLogs() ([]byte, error) {
	ret := _m.Called()

	if len(ret) == 0 {
		panic("no return value specified for GetLogs")
	}

	var r0 []byte
	var r1 error
	if rf, ok := ret.Get(0).(func() ([]byte, error)); ok {
		return rf()
	}
	if rf, ok := ret.Get(0).(func() []byte); ok {
		r0 = rf()
	} else {
		if ret.Get(0) != nil {
			r0 = ret.Get(0).([]byte)
		}
	}

	if rf, ok := ret.Get(1).(func() error); ok {
		r1 = rf()
	} else {
		r1 = ret.Error(1)
	}

	return r0, r1
}

// MockDiagnosticsService_GetLogs_Call is a *mock.Call that shadows Run/Return methods with type explicit version for method 'GetLogs'
type MockDiagnosticsService_GetLogs_Call struct {
	*mock.Call
}

// GetLogs is a helper method to define mock.On call
func (_e *MockDiagnosticsService_Expecter) GetLogs() *MockDiagnosticsService_GetLogs_Call {
	return &MockDiagnosticsService_GetLogs_Call{Call: _e.mock.On("GetLogs")}
}

func (_c *MockDiagnosticsService_GetLogs_Call) Run(run func()) *MockDiagnosticsService_GetLogs_Call {
	_c.Call.Run(func(args mock.Arguments) {
		run()
	})
	return _c
}

func (_c *MockDiagnosticsService_GetLogs_Call) Return(_a0 []byte, _a1 error) *MockDiagnosticsService_GetLogs_Call {
	_c.Call.Return(_a0, _a1)
	return _c
}

func (_c *MockDiagnosticsService_GetLogs_Call) RunAndReturn(run func() ([]byte, error)) *MockDiagnosticsService_GetLogs_Call {
	_c.Call.Return(run)
	return _c
}

// GetLogsAsZip provides a mock function with given fields: startDate, stopDate
func (_m *MockDiagnosticsService) GetLogsAsZip(startDate *time.Time, stopDate *time.Time) ([]byte, error) {
	ret := _m.Called(startDate, stopDate)

	if len(ret) == 0 {
		panic("no return value specified for GetLogsAsZip")
	}

	var r0 []byte
	var r1 error
	if rf, ok := ret.Get(0).(func(*time.Time, *time.Time) ([]byte, error)); ok {
		return rf(startDate, stopDate)
	}
	if rf, ok := ret.Get(0).(func(*time.Time, *time.Time) []byte); ok {
		r0 = rf(startDate, stopDate)
	} else {
		if ret.Get(0) != nil {
			r0 = ret.Get(0).([]byte)
		}
	}

	if rf, ok := ret.Get(1).(func(*time.Time, *time.Time) error); ok {
		r1 = rf(startDate, stopDate)
	} else {
		r1 = ret.Error(1)
	}

	return r0, r1
}

// MockDiagnosticsService_GetLogsAsZip_Call is a *mock.Call that shadows Run/Return methods with type explicit version for method 'GetLogsAsZip'
type MockDiagnosticsService_GetLogsAsZip_Call struct {
	*mock.Call
}

// GetLogsAsZip is a helper method to define mock.On call
//   - startDate *time.Time
//   - stopDate *time.Time
func (_e *MockDiagnosticsService_Expecter) GetLogsAsZip(startDate interface{}, stopDate interface{}) *MockDiagnosticsService_GetLogsAsZip_Call {
	return &MockDiagnosticsService_GetLogsAsZip_Call{Call: _e.mock.On("GetLogsAsZip", startDate, stopDate)}
}

func (_c *MockDiagnosticsService_GetLogsAsZip_Call) Run(run func(startDate *time.Time, stopDate *time.Time)) *MockDiagnosticsService_GetLogsAsZip_Call {
	_c.Call.Run(func(args mock.Arguments) {
		run(args[0].(*time.Time), args[1].(*time.Time))
	})
	return _c
}

func (_c *MockDiagnosticsService_GetLogsAsZip_Call) Return(_a0 []byte, _a1 error) *MockDiagnosticsService_GetLogsAsZip_Call {
	_c.Call.Return(_a0, _a1)
	return _c
}

func (_c *MockDiagnosticsService_GetLogsAsZip_Call) RunAndReturn(run func(*time.Time, *time.Time) ([]byte, error)) *MockDiagnosticsService_GetLogsAsZip_Call {
	_c.Call.Return(run)
	return _c
}

// GetLogsByDate provides a mock function with given fields: startDate, stopDate
func (_m *MockDiagnosticsService) GetLogsByDate(startDate *time.Time, stopDate *time.Time) ([]byte, error) {
	ret := _m.Called(startDate, stopDate)

	if len(ret) == 0 {
		panic("no return value specified for GetLogsByDate")
	}

	var r0 []byte
	var r1 error
	if rf, ok := ret.Get(0).(func(*time.Time, *time.Time) ([]byte, error)); ok {
		return rf(startDate, stopDate)
	}
	if rf, ok := ret.Get(0).(func(*time.Time, *time.Time) []byte); ok {
		r0 = rf(startDate, stopDate)
	} else {
		if ret.Get(0) != nil {
			r0 = ret.Get(0).([]byte)
		}
	}

	if rf, ok := ret.Get(1).(func(*time.Time, *time.Time) error); ok {
		r1 = rf(startDate, stopDate)
	} else {
		r1 = ret.Error(1)
	}

	return r0, r1
}

// MockDiagnosticsService_GetLogsByDate_Call is a *mock.Call that shadows Run/Return methods with type explicit version for method 'GetLogsByDate'
type MockDiagnosticsService_GetLogsByDate_Call struct {
	*mock.Call
}

// GetLogsByDate is a helper method to define mock.On call
//   - startDate *time.Time
//   - stopDate *time.Time
func (_e *MockDiagnosticsService_Expecter) GetLogsByDate(startDate interface{}, stopDate interface{}) *MockDiagnosticsService_GetLogsByDate_Call {
	return &MockDiagnosticsService_GetLogsByDate_Call{Call: _e.mock.On("GetLogsByDate", startDate, stopDate)}
}

func (_c *MockDiagnosticsService_GetLogsByDate_Call) Run(run func(startDate *time.Time, stopDate *time.Time)) *MockDiagnosticsService_GetLogsByDate_Call {
	_c.Call.Run(func(args mock.Arguments) {
		run(args[0].(*time.Time), args[1].(*time.Time))
	})
	return _c
}

func (_c *MockDiagnosticsService_GetLogsByDate_Call) Return(_a0 []byte, _a1 error) *MockDiagnosticsService_GetLogsByDate_Call {
	_c.Call.Return(_a0, _a1)
	return _c
}

func (_c *MockDiagnosticsService_GetLogsByDate_Call) RunAndReturn(run func(*time.Time, *time.Time) ([]byte, error)) *MockDiagnosticsService_GetLogsByDate_Call {
	_c.Call.Return(run)
	return _c
}

// Name provides a mock function with given fields:
func (_m *MockDiagnosticsService) Name() string {
	ret := _m.Called()

	if len(ret) == 0 {
		panic("no return value specified for Name")
	}

	var r0 string
	if rf, ok := ret.Get(0).(func() string); ok {
		r0 = rf()
	} else {
		r0 = ret.Get(0).(string)
	}

	return r0
}

// MockDiagnosticsService_Name_Call is a *mock.Call that shadows Run/Return methods with type explicit version for method 'Name'
type MockDiagnosticsService_Name_Call struct {
	*mock.Call
}

// Name is a helper method to define mock.On call
func (_e *MockDiagnosticsService_Expecter) Name() *MockDiagnosticsService_Name_Call {
	return &MockDiagnosticsService_Name_Call{Call: _e.mock.On("Name")}
}

func (_c *MockDiagnosticsService_Name_Call) Run(run func()) *MockDiagnosticsService_Name_Call {
	_c.Call.Run(func(args mock.Arguments) {
		run()
	})
	return _c
}

func (_c *MockDiagnosticsService_Name_Call) Return(_a0 string) *MockDiagnosticsService_Name_Call {
	_c.Call.Return(_a0)
	return _c
}

func (_c *MockDiagnosticsService_Name_Call) RunAndReturn(run func() string) *MockDiagnosticsService_Name_Call {
	_c.Call.Return(run)
	return _c
}

// Pass provides a mock function with given fields:
func (_m *MockDiagnosticsService) Pass() bool {
	ret := _m.Called()

	if len(ret) == 0 {
		panic("no return value specified for Pass")
	}

	var r0 bool
	if rf, ok := ret.Get(0).(func() bool); ok {
		r0 = rf()
	} else {
		r0 = ret.Get(0).(bool)
	}

	return r0
}

// MockDiagnosticsService_Pass_Call is a *mock.Call that shadows Run/Return methods with type explicit version for method 'Pass'
type MockDiagnosticsService_Pass_Call struct {
	*mock.Call
}

// Pass is a helper method to define mock.On call
func (_e *MockDiagnosticsService_Expecter) Pass() *MockDiagnosticsService_Pass_Call {
	return &MockDiagnosticsService_Pass_Call{Call: _e.mock.On("Pass")}
}

func (_c *MockDiagnosticsService_Pass_Call) Run(run func()) *MockDiagnosticsService_Pass_Call {
	_c.Call.Run(func(args mock.Arguments) {
		run()
	})
	return _c
}

func (_c *MockDiagnosticsService_Pass_Call) Return(_a0 bool) *MockDiagnosticsService_Pass_Call {
	_c.Call.Return(_a0)
	return _c
}

func (_c *MockDiagnosticsService_Pass_Call) RunAndReturn(run func() bool) *MockDiagnosticsService_Pass_Call {
	_c.Call.Return(run)
	return _c
}

// UploadLogs provides a mock function with given fields: url, startDate, stopDate, retryInterval, retries
func (_m *MockDiagnosticsService) UploadLogs(url string, startDate *time.Time, stopDate *time.Time, retryInterval time.Duration, retries int) error {
	ret := _m.Called(url, startDate, stopDate, retryInterval, retries)

	if len(ret) == 0 {
		panic("no return value specified for UploadLogs")
	}

	var r0 error
	if rf, ok := ret.Get(0).(func(string, *time.Time, *time.Time, time.Duration, int) error); ok {
		r0 = rf(url, startDate, stopDate, retryInterval, retries)
	} else {
		r0 = ret.Error(0)
	}

	return r0
}

// MockDiagnosticsService_UploadLogs_Call is a *mock.Call that shadows Run/Return methods with type explicit version for method 'UploadLogs'
type MockDiagnosticsService_UploadLogs_Call struct {
	*mock.Call
}

// UploadLogs is a helper method to define mock.On call
//   - url string
//   - startDate *time.Time
//   - stopDate *time.Time
//   - retryInterval time.Duration
//   - retries int
func (_e *MockDiagnosticsService_Expecter) UploadLogs(url interface{}, startDate interface{}, stopDate interface{}, retryInterval interface{}, retries interface{}) *MockDiagnosticsService_UploadLogs_Call {
	return &MockDiagnosticsService_UploadLogs_Call{Call: _e.mock.On("UploadLogs", url, startDate, stopDate, retryInterval, retries)}
}

func (_c *MockDiagnosticsService_UploadLogs_Call) Run(run func(url string, startDate *time.Time, stopDate *time.Time, retryInterval time.Duration, retries int)) *MockDiagnosticsService_UploadLogs_Call {
	_c.Call.Run(func(args mock.Arguments) {
		run(args[0].(string), args[1].(*time.Time), args[2].(*time.Time), args[3].(time.Duration), args[4].(int))
	})
	return _c
}

func (_c *MockDiagnosticsService_UploadLogs_Call) Return(_a0 error) *MockDiagnosticsService_UploadLogs_Call {
	_c.Call.Return(_a0)
	return _c
}

func (_c *MockDiagnosticsService_UploadLogs_Call) RunAndReturn(run func(string, *time.Time, *time.Time, time.Duration, int) error) *MockDiagnosticsService_UploadLogs_Call {
	_c.Call.Return(run)
	return _c
}

// NewMockDiagnosticsService creates a new instance of MockDiagnosticsService. It also registers a testing interface on the mock and a cleanup function to assert the mocks expectations.
// The first argument is typically a *testing.T value.
func NewMockDiagnosticsService(t interface {
	mock.TestingT
	Cleanup(func())
}) *MockDiagnosticsService {
	mock := &MockDiagnosticsService{}
	mock.Mock.Test(t)

	t.Cleanup(func() { mock.AssertExpectations(t) })

	return mock
}
