name: Build ChargePi docker image

on:
  push:
    branches:
      - main

jobs:
  build:
    name: Build a Docker image
    runs-on: ubuntu-latest

    steps:
      - name: Checkout code
        uses: actions/checkout@v3

      - name: Set up QEMU
        uses: docker/setup-qemu-action@v2

      - name: Login to Docker Hub
        uses: docker/login-action@v2
        with:
          username: ${{ secrets.DOCKER_HUB_USERNAME }}
          password: ${{ secrets.DOCKER_HUB_ACCESS_TOKEN }}

      - name: Set up Docker Buildx
        id: buildx
        uses: docker/setup-buildx-action@v1

      - name: Build and push
        uses: docker/build-push-action@v2
        with:
          context: .
          target: chargepi
          build-args: --build-arg READER_CONNECTION_TYPE="pn532_uart"
          file: ./build/package/Dockerfile
          platforms: linux/arm64
          push: true
          tags: ${{ secrets.DOCKER_HUB_USERNAME }}/chargepi:latest