name: "Test and lint"

on:
  push:
    branches:
      - main
      - v2
    paths-ignore:
      - '.run/**'
      - 'docs/**'
      - 'deployments/**'
      - 'scripts/**'
      - '*.md'

  pull_request:
    branches:
      - main
      - v2
    types: [ opened, synchronize ]
    paths-ignore:
      - '.run/**'
      - 'docs/**'
      - 'deployments/**'
      - 'scripts/**'
      - '*.md'

jobs:
  # Run unit tests
  unit:
    name: "Run unit tests"
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v4

      - name: Setup Go
        uses: actions/setup-go@v5
        with:
          go-version: 1.23.0

        # todo skip mocks coverage
      - name: Install dependencies and run tests
        run: |
          go mod download
          go test -v ./... -coverpkg=./... -short -coverprofile=unit_coverage.out

  integration:
    name: "Run integration tests"
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v4

      - name: Setup Go
        uses: actions/setup-go@v5
        with:
          go-version: 1.23.0

      - name: Install dependencies and run tests
        run: |
          go mod download
          go test -v -run 'Integration$' ./... -coverpkg=./... -coverprofile=integration_coverage.out