name: Test ChargePi

on:
  pull_request:
    branches:
      - main

jobs:
  testing:
    name: Run unit tests
    runs-on: ubuntu-latest

    steps:

      - name: Checkout code
        uses: actions/checkout@v2

      - name: Set up Go
        uses: actions/setup-go@v2
        with:
          go-version: "^1.17"

      - name: Build
        env:
          GOOS: linux
          GOARCH: amd64
        run: go build .

      - name: Test
        run: go test --short -v ./...
